### PR TITLE
Lower the democracy requirements

### PR DESCRIPTION
**Pull request by sugar700**
Let's have a truer democracy. Anybody who knows anything about code should be equal.

Note that this project has a requirement of account being sufficiently old, so abusers creating multiple accounts won't be able to do anything anyway.

### CODE REVIEW

**Comment by sugar700** [comment]
... although that makes me wonder, the requirement is 1 month, but somebody may create spam bots today to be able to merge pretty much anything in a month. I suppose that may be looked on later??

**Comment by amoffat** [comment]
there are tradeoffs to this:

```ipython
In [2]: log(345, 30)
Out[2]: 1.7180844747609552

In [3]: log(345, 15)
Out[3]: 2.1578419833771787
```

**Comment by joarwilk** [comment]
👍

**Comment by sangohan** [comment]
👍

**Pull request closed without merging**
