### PR TITLE
Encryption, take 4 

### PR DESCRIPTION
**Pull request by sugar700**
#225 was rejected, as I was unfortunate enough to put a pull request exactly when voting window ended.

### CODE REVIEW

**Comment by sugar700** [comment]
Okay, what's going on.

**Comment by sugar700** [comment]
Seriously, uhh....

**Comment by sugar700** [comment]
Hm, but passing votes is feasible, if there would be coordination, it could be possible to put three required votes (other than mine) in a few seconds.

**Comment by sugar700** [comment]
But probably the first pull request in order would be one that fixes this nonsense.

**Comment by amoffat** [comment]
i think this is related to the quirk/critical problem where chaos determines the voting window from your last commit push

**Comment by sugar700** [comment]
Oh.

**Comment by amoffat** [comment]
https://github.com/chaosbot/chaos/issues/199 for details

**Comment by amoffat** [comment]
if you push a dummy commit and open the PR, it should be fine

**Pull request closed without merging**
