### PR TITLE
Add ESLint to lint JS files

### PR DESCRIPTION
**Pull request by mdcfe**
Currently uses `eslint-config-airbnb` with indents of 4 and double quotes.

### CODE REVIEW

**Comment by mdcfe** [comment]
For some reason Travis is using an ancient version of node - fixing now.

**Comment by andrewda** [comment]
Yea that's super old

**Comment by rhengles** [comment]
While you're at it, can you also add Prettier ?

**Comment by mdcfe** [comment]
@rhengles As far as I can tell, running Prettier inside Travis won't have any effect on the code in the repo, nor will it change the CI results. It also conflicts with `eslint-config-airbnb`.

**Comment by mdcfe** [comment]
I'm working on making all of the existing code pass ESLint ~~- it will be in a separate PR. For now, this can be merged even though it's failing.~~

**Comment by andrewda** [comment]
All those linting errors need to be fixed or ignored before merging into master - maybe make this WIP unless you think you can fix them in 3 hrs?

**Comment by PlasmaPower** [comment]
We shouldn't push a failing build to master - fix the errors first.

Edit: -1 rescinded

**Comment by mdcfe** [comment]
@andrewda @PlasmaPower I've gone through the errors much quicker than I expected, so I'll push the changes to this PR instead.

**Review by PlasmaPower — APPROVED** [review]
Travis passing!

**Comment by andrewda** [comment]
@md678685 I think you missed the path to the configuration file in the eslint command. It's showing a usage message on Travis.

**Comment by mdcfe** [comment]
@andrewda Oops, I'll take a look now.

**Review by andrewda — APPROVED** [review]
Looks good!

**Review by andrewda — APPROVED** [review]
oops approved wrong commit ;)

**Comment by PlasmaPower** [comment]
Conflicts :(

**Comment by mdcfe** [comment]
@PlasmaPower Merged again, hopefully should be fine now.

**Comment by PlasmaPower** [comment]
Looks like the merge added in some eslint problems.

**Comment by mdcfe** [comment]
...or not. I'll fix it now :/

**Comment by mdcfe** [comment]
👍 Oops, I think I downvoted it with a `:confused:` emoji

Either way, that's just bumped up the voting window by another few hours :/

**Review by PlasmaPower — APPROVED** [review]

**Review by RyanZim — APPROVED** [review]

**Pull request merged**
