### PR TITLE
WIP: how 2 solve merge failures?

### PR DESCRIPTION
**Pull request by amoffat**
Scenario:

1. User A creates PR 1, gets 20 yay votes
2. User B creates PR 2, gets 20 yay votes
3. Voting window passes on A and B
4. Chaosbot collects PRs 1 and 2 for consideration
5. Chaosbot merges PR 1
6. PR 2 had edited the same lines, now there's a merge conflict
7. Chaosbot doesn't merge PR 2, tags it as `can't merge`
7. User B pulls from upstream/master, creating a merge commit on his branch, re-pushes his code
8. Chaosbot looks at PR 2 and sees User B's branch was updated very recently
9. Chaosbot ignores all previous 20 votes because they are now older than the most recent change
10. Chaosbot doesn't merge PR 2
11. Chaosbot hates you

feelsbadman.jpg

### CODE REVIEW

**Comment by studiosi** [comment]
Maybe the latter changeset should always prevail?

I think, though that this move opens a window for trolls to just kill the server, as long as they get enough agreement to push a PR. This can happen anyways, though.

**Comment by OpenNingia** [comment]
Losing votes is bad, especially if you just want to rebase your PR. I believe that exposing the bot to troll PR is the necessary evil.

**Comment by Jezza** [comment]
Why not just get chaosbot to recheck PRs it labelled as can't merge?  
The contributor can fix it, and push the changes, and when chaosbot goes to remerge it, it can.  
PRs don't lose votes on a merge conflict, and the contributor can still fix the issue.

**Comment by Jezza** [comment]
Basically, have an edge case specifically for repositories chaosbot couldn't merge. 
It would be pretty easy to keep track of that.

**Comment by amoffat** [comment]
this has been solved by the code that keeps you from losing votes

**Pull request closed without merging**
