### PR TITLE
Database abstraction layer (sqlite implementation)

### PR DESCRIPTION
**Pull request by hongaar**
```python
db = DB.get_instance()  # type: DB

db.query("DROP TABLE IF EXISTS users ")
db.query("CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name TEXT NOT NULL)")
db.query("INSERT INTO users (name) VALUES (?)", ['test1'])
db.query("INSERT INTO users (name) VALUES (?)", ['test2'])
db.query("INSERT INTO users (name) VALUES (?)", ['test3'])

print(db.query("SELECT * FROM users"))
print(db.row("SELECT * FROM users"))
print(db.one("SELECT * FROM users"))
```
⏬ 
```
[(1, 'test1'), (2, 'test2'), (3, 'test3')]
(1, 'test1')
1
```

### CODE REVIEW

**Comment by flibustier** [comment]
The PR we all expected! Great :)

**Comment by flibustier** [comment]
Well done!!
Next step : Blockchain :D

**Comment by mdcfe** [comment]
The web server currently runs in its own process, and as far as I know so do the cron jobs? I think we should go with MySQL, purely because it's practically guaranteed that we can modify it concurrently without interfering with other processes or having to wait for locks.

**Comment by hongaar** [comment]
@md678685 you're in luck: https://github.com/chaosbot/Chaos/pull/461

_edit_ if you vote that one up, you'll be implicitly also voting this one up 😄

**Comment by rudehn** [comment]
I'm going to add a hook to the DB class to support an ORM as well. I'd just prefer not having to rewrite any queries and have the ORM do it all for me  😄

**Comment by PlasmaPower** [comment]
We're just merging the mysql PR as it includes this one, right? Or was this one supposed to go through too?

**Pull request closed without merging**
