### PR TITLE
Add a little personality to the bot

### PR DESCRIPTION
**Pull request by Niximacco**
Just adds some emoji to the bot. :ok_woman: and :no_good_woman:

### CODE REVIEW

**Comment by sosodev** [comment]
👎 emojis are too boring

**Comment by eighthjouster** [comment]
And yet you're using them instead of using another form of voting, @simplyserenity?

**Comment by eighthjouster** [comment]
👍

**Comment by dragbone** [comment]
👍

**Comment by patricknelson** [comment]
👍 this combined with an implementation of `cowsay` mentioned here https://github.com/chaosbot/chaos/commit/506c1ec420b808b2c4035bbd556515feb0bb193e 🐮

**Comment by philals** [comment]
👍

**Comment by jnnnnn** [comment]
👎

**Pull request merged**
