### PR TITLE
Change meritocracy distribution

### PR DESCRIPTION
**Pull request by PlasmaPower**
I think this will be a bit better, as IMO contributing is more important than voting

### CODE REVIEW

**Comment by andrewda** [comment]
I think we should keep the total at 20 (because in reality it would be more like 10-12 after the duplicates). 12 and 8 would probably be good, or 14 and 6.

**Comment by PlasmaPower** [comment]
@andrewda Overlaps reduce that though - I'll calculate what change this'll have.

**Comment by PlasmaPower** [comment]
This would reduce the size of the current meritocracy, but only from 15 to 14.

**Comment by andrewda** [comment]
Ok that works for me. But I think that mentioning the members of the meritocracy when entering the extended voting period is a must, especially because his will change the meritocrats.

**Comment by PlasmaPower** [comment]
@andrewda I'd prefer to do that after the DB PR gets merged. It'll be a lot more stable then.

**Comment by andrewda** [comment]
Yep works for me (as long as it's done pretty soon)

**Comment by PlasmaPower** [comment]
Merge conflicts fixed. I'll start working on the meritocracy mentions now.

**Comment by rudehn** [comment]
I think the meritocracy balance might need to be tweaked. I'm not sure the top 5 voters is useful, since pretty much all of them are already in the meritocracy

**Review by andrewda — APPROVED** [review]

**Comment by PlasmaPower** [comment]
@rudehn Pretty much all, but not all. That could also change. IMHO top voters isn't useful, but I added it due to popular approval.

**Comment by hongaar** [comment]
I'd say voters should be in there somehow, maybe even number of comments on issues/PRs? That way we 'reward' contributions from the community who doesn't actually write code.

**Comment by andrewda** [comment]
That's a good point @hongaar - something like the judicial branch of the Chaosbot democracy

**Comment by PlasmaPower** [comment]
@hongaar I'd support that, but the implementation might be complicated.

**Comment by andrewda** [comment]
@PlasmaPower it would be much easier when database stuff gets up and running

**Comment by PlasmaPower** [comment]
One vote needed.

**Comment by PlasmaPower** [comment]
Or maybe 2, there's a decimal behind the `.5`.

**Comment by PlasmaPower** [comment]
@anythingbot well it's a good think I don't care :)

**Comment by PlasmaPower** [comment]
@anythingbot that'd be a republic, not a meritocracy. I've also considered it, but I think the current solution works fine.

**Pull request closed without merging**
