### PR TITLE
🗳 Bring back democracy

### PR DESCRIPTION
**Pull request by hongaar**
Cast your votes, they'll be pointless anyway. 😆

See #138

Our only chance of going back to some form of democracy is if this PR will get the approval of @PlasmaPower.

### CODE REVIEW

**Comment by tarunbatra** [comment]
Grace @PlasmaPower, you mean. 😆

**Review by MINIMAN10000 — APPROVED** [review]

**Comment by PlasmaPower** [comment]
:100: This PR has been approved by your benevolent dictator, PlasmaPower.

**Comment by PlasmaPower** [comment]
Not sure what the merge window is right now, but it still applies. I couldn't change it because it'd cause a merge conflict.

**Comment by PlasmaPower** [comment]
Looks like we have an hour before this PR merges.

**Comment by ECrownofFire** [comment]
@hongaar You should probably stop pushing to your fork until this PR gets approved :P

**Comment by hongaar** [comment]
I'll hold my horses for a while 😉

**Comment by rudehn** [comment]
Still not in? Did we break something?

**Comment by hongaar** [comment]
Server is down..

**Comment by PlasmaPower** [comment]
:( I was very careful not to break anything, what went wrong? Or maybe it wasn't my commit? Maybe it was the owner downvote change attached to it?

**Comment by ECrownofFire** [comment]
It broke a few hours after the last commit. The last thing it was doing is checking to see if the homepage crashed. Maybe it somehow got stuck in an infinite loop? Trying to connect to http://chaosthebot.com just hangs with no response, so the bot is still running.

**Comment by reddraggone9** [comment]
Logs for reference: http://chaosthebot.com:8081/chaos-stderr---supervisor-lSIrBd.log

The stuff you people get up to while I'm asleep...

**Comment by hongaar** [comment]
See https://github.com/chaosbot/chaos/issues/175

**Comment by hongaar** [comment]
🎉

**Comment by patricknelson** [comment]
That's hilarious 😂 . Thank you @PlasmaPower 🌷 our benevolent dictator of 10 hours, 26 minutes and 11 seconds!

**Pull request merged**
