### PR TITLE
Make @smittyvb votes count less

### PR DESCRIPTION
**Pull request by yet-another-account**
Don't worry, this is just a joke.

### CODE REVIEW

**Comment by phil-r** [comment]
Well, there is some sense in this, @Smittyvb attempted to take over multiple times and haven't even tried to contribute anything helpful

**Comment by yet-another-account** [comment]
I love how @smittyvb is the only one who has downvoted this. Maybe we should expand this to a full blown banlist, on which your voting power is cut in half.

**Comment by PlasmaPower** [comment]
No, we should double the threshold for their PRs, not halve the voting power.

**Comment by yet-another-account** [comment]
@PlasmaPower why not both?

**Comment by yet-another-account** [comment]
I'm not sure how to implement that, so you can do it

**Comment by mark-i-m** [comment]
> I'm not sure how to implement that

After computing the total weighted sum, you can halve it before checking if it meets the threshold

**Comment by PlasmaPower** [comment]
@eukaryote31 For this PR, could you read from a file? I'll make a PR for the threshold after that.

**Pull request merged**
