### PR TITLE
Fix meritocracy.json serialization

### PR DESCRIPTION
**Pull request by PlasmaPower**
As broken by #462

### CODE REVIEW

**Comment by rudehn** [comment]
Seems like we need better exception handling everywhere

**Review by phil-r — APPROVED** [review]
Confirmed, works

**Comment by PlasmaPower** [comment]
@rudehn Agreed, I always add exception handling to my PRs when possible. I'll start recommending it too.

**Comment by mdcfe** [comment]
Oops, thanks for fixing this.

**Comment by PlasmaPower** [comment]
@mark-i-m It seems to me like the time remaining for this PR is wrong, and it's been jumping around a lot. The same has happened with my other PRs. I'm using this PR as the example because I've never amended the commit. Ideas why?

**Comment by andrewda** [comment]
@PlasmaPower the bot's still on vacation from the GitHub API cooldown http://chaosthebot.com:8081/chaos-stderr.log – should probably be back in like 14-15 mins.

**Comment by PlasmaPower** [comment]
@andrewda Oh I thought it was already back, oops. Get ready for a lot of merges! :tada:

**Comment by PlasmaPower** [comment]
Is another issue at play? I'd expect this to be merged by now. The count is going down properly.

**Comment by andrewda** [comment]
When the bot came back it reset many PR's to 2:30. Not sure what the issue is.

**Review by andrewda — APPROVED** [review]

**Comment by PlasmaPower** [comment]
I think it might loose the push events and fall back to repo `pushed_at`.

**Comment by PlasmaPower** [comment]
The rollback feature is in effect, right? I think that means no new changes will take effect until this gets merged.

**Comment by andrewda** [comment]
I think so.

**Comment by PlasmaPower** [comment]
Odd, some PRs seem to be merging. Could it be the extended voting window misfiring? It tends to do that :confused:.

**Comment by PlasmaPower** [comment]
Well, I'm going to sleep. Do me a favor and don't break chaosbot :smile:.

**Comment by andrewda** [comment]
Whelp, it's doing another hour-long vacation. Guess I'll go to sleep...

```
06-02 05:37 github_api   DEBUG    requests remaining: 16, reset in: 3595s, cooldown sleep: 3625.84s
```

**Comment by hongaar** [comment]
Maybe instead of `remaining: 01:30` the status post should include `deadline: 17:43 GMT`, `last updated: 16:13 GMT`, or both? Although then the status won't fit on a single line again...
Or provide a details link to our website (:+1:) with more info on current votes and a deadline/last updated time in your local timezone using [momentjs](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/).

**Pull request merged**
