### PR TITLE
Make @smittyvb votes worth about (e^pi-pi)/40

### PR DESCRIPTION
**Pull request by yet-another-account**
Which is about 0.49997749948. Just for the lols. 

Seriously, though, it's a joke. Although, it would be funny to be ~0.000022 away from the voting threshold.

### CODE REVIEW

**Comment by yet-another-account** [comment]
@smittyvb would you upvote if I made it 1-(e^pi-pi)/40? That would make your voting power 0.50002250052, or about 0.000023 MORE than you currently have right now! Win-win, amirite?

**Comment by syvb** [comment]
Yep.

**Comment by yet-another-account** [comment]
There you go!

**Comment by o3LL** [comment]
Unfair 😂

**Pull request closed without merging**
