### PR TITLE
Remove the Rickroll

### PR DESCRIPTION
**Pull request by xyproto**
To quote a [random poem](https://www.familyfriendpoems.com/poem/carry-on) I found online:

> I don't hate you, 
> Because I still love you. 
> I can't look at you, 
> Because it hurts to.
> We don't talk, 
> Because there is nothing left to say.

The Rick Roll has had its golden age. It's time to let it go.

### CODE REVIEW

**Comment by davidak** [comment]
Luckily it's banned in germany!

bildschirmfoto von 2017-05-24 11 18 38

**Review by sp-1234 — CHANGES_REQUESTED** [review]
no

**Comment by dehodson** [comment]
Wonderful PR. ☑️

**Comment by rudehn** [comment]
Try this again with #153 accepted

**Comment by xyproto** [comment]
Opened #202, but now there are merge conflicts

**Pull request closed without merging**
