### PR TITLE
Add logtail log viewer

### PR DESCRIPTION
**Pull request by yet-another-account**
Now we should be able to watch the logs roll in live, rather than having to download a huge log file.

### CODE REVIEW

**Review by amoffat — COMMENTED** [review]
cdn for jquery?

**Comment by yet-another-account** [comment]
There, fixed.

**Comment by reddraggone9** [comment]
This uses byte ranges to get pieces of the log file. That won't work because:
1. The server currently serving that directory doesn't support the range header. I tested this locally using
   ```sh
   python3 -m http.server
   # on a separate terminal
   echo 'a test file' > test
   curl -v -X GET -H "range: bytes=1-4" http://localhost:8000/test
   ```
   which gave me the whole file.
2. The logs are rolling. A section of the file indexed by byte ranges won't always be the same.

**Comment by hongaar** [comment]
Not in a position to test currently, but big fan of the idea!

**Pull request closed without merging**
