### PR TITLE
Add test for TEST to be False

### PR DESCRIPTION
**Pull request by phil-r**
Sorry @paris-ci and @Ayyko, no fun 😐

Also removed print

### CODE REVIEW

**Comment by phil-r** [comment]
It's a followup to #379 #98 #190 #188 and #410

**Comment by PlasmaPower** [comment]
:-1: then people'll change the tests too

**Comment by Ayyko** [comment]
First they come for your test settings, but you do not care. Next they come for your votes, but you were asleep during the voting window.
Finally, they come for you. :-1: idk how to do that on mobile so hopefully it works

**Comment by phil-r** [comment]
@PlasmaPower Now they know how to circumvent this ;(

**Review by rhengles — APPROVED** [review]

**Pull request closed without merging**
