### PR TITLE
pip install ansible

### PR DESCRIPTION
**Pull request by pchauncey**
Adding ansible to `requirements.txt`

### CODE REVIEW

**Comment by g19fanatic** [comment]
already have puppet, why need ansible?  :)

vim/emacs type discussion about to occur... :zap: :fire:

**Comment by pchauncey** [comment]
Given the democratic nature of the project, I suggest we enable people with the hammers of their choice

**Comment by ECrownofFire** [comment]
@pchauncey For when all you have is nails?

**Comment by hongaar** [comment]
Why not add it when it's needed?

**Pull request merged**
