### PR TITLE
Make crash report labels red

### PR DESCRIPTION
**Pull request by mark-i-m**
I didn't know you could even do this!

### CODE REVIEW

**Review by PlasmaPower — APPROVED** [review]

**Review by Swizz — APPROVED** [review]
I will not take credits :3

**Review by o3LL — APPROVED** [review]

**Review by andrewda — APPROVED** [review]

**Comment by mark-i-m** [comment]
Why did @chaosbot post that? Didn't @PlasmaPower approve the changes an hour before?

**Comment by PlasmaPower** [comment]
@mark-i-m yep, it's super broken. See #500

**Comment by mark-i-m** [comment]
Ah, I didn't realize they were the same issue

**Comment by PlasmaPower** [comment]
@mark-i-m that PR fixes a ton of issues

**Pull request merged**
