### PR TITLE
Ｕｐｄａｔｅ　ＲＥＡＤＭＥ　ｗｉｔｈ　ＯＳ

### PR DESCRIPTION
**Pull request by richardanaya**

### CODE REVIEW

**Comment by agargiulo** [comment]
What are you doing to all your PR titles and why?

**Comment by richardanaya** [comment]
Chaos

**Review by AndreiRailean — APPROVED** [review]

**Comment by agargiulo** [comment]
Is that some sort of weird web font junk?

**Comment by demiters** [comment]
Good lord what's with the title font, I'm inclined to downvote all of these for that.

**Comment by nurupo** [comment]
It's the same font as always. Only GitHub can change the font of the issue title, there is no way for a GitHub user to change the font to, say, Comic Sans, or some [web font](https://fonts.google.com/). The letters used in the font, however, are not your regular Latin letters, those are full-width Latin letters. [Here is the Unicode range for them](http://unicode.org/charts/PDF/UFF00.pdf).

**Comment by agargiulo** [comment]
Oh that's more vile. (And more what I was thinking but making jokes about web fonts is fun)

**Comment by demiters** [comment]
Accepting these chaotic titles sets a bad precedent! :confused:

**Comment by ashleysommer** [comment]
Also not liking the full-width characters in the title.

**Comment by ghost** [comment]
I'm all for nominating @demiters as wet blanket of the year 2017

**Pull request merged**
