### PR TITLE
Add (almost) unclickable link to github page

### PR DESCRIPTION
**Pull request by fbermel**
I believe it's important to show people how to contribute to this awesome project so I've added a link to the github page.
It also doubles as patience trial for possible new contributors.

### CODE REVIEW

**Comment by jabbink** [comment]
`<TAB><RETURN>`

**Review by pchauncey — APPROVED** [review]

**Comment by dragondave** [comment]
Consider using `screen.height` and `screen.width`?

**Comment by fbermel** [comment]
> Consider using screen.height and screen.width?

I believe it would be even better to use `window.innerWidth` and `window.innerHeight` to make it relative to the size of the browser window.

**Comment by HxxxxxS** [comment]
👍

**Comment by amloelxer** [comment]
👍

**Review by m1guelpf — APPROVED** [review]

**Comment by samis** [comment]
:+1:

**Pull request merged**
