### PR TITLE
adding masterless puppet

### PR DESCRIPTION
**Pull request by g19fanatic**
Against #114 

Will allow a way to manage the underlying VPS in a configuration managed way without needing to run servers.

### CODE REVIEW

**Comment by g19fanatic** [comment]
Any discussion on why people think this is a bad idea?

**Comment by rudehn** [comment]
Can you perhaps explain a little more what you want to do?

**Comment by g19fanatic** [comment]
Puppet is an open source configuration management system used to describe system configuration. This will allow us to setup the vps with explicit changes/modules to configure everything you'd be able to configure as a system admin, through chaos voting.

Let's say someone wants to create a front end nginx proxy, that can be done straight from a puppet module in a declarative manner without needing worrying about mistakes in scripts and putting the system in s bad state. Puppet modules allow you to keep the configuration explicitly defined as described.

**Comment by g19fanatic** [comment]
Just want to create the base for the opportunity to install and manage everything else on the vps. Modules can be added as separate PRs. It would be easy to add anything to the vps using a system such as puppet.

Other similar tools are ansible, chef, salt... Etc...

**Comment by howdoicomputer** [comment]
I like the idea but I don't like Puppet so I'm uncertain of whether or not I want to put in an upvote.

**Comment by patricknelson** [comment]
This is actually a good idea, since this'll make it easier to provision the VM this lives on. Also in my local `Vagrantfile` I can ensure my local dev environment is consistent w/ production (see #123)

**Comment by howdoicomputer** [comment]
lol it merges on a tie

**Comment by amoffat** [comment]
@howdoicomputer non-binary vote weights are [still being used](https://github.com/chaosbot/chaos/commit/09117aed7f3b8d52f8856b2447177ab37bf06841)...they were [cached](https://github.com/chaosbot/chaos/blob/master/patch.py#L36) for 1 day to disk.

**Comment by howdoicomputer** [comment]
Thanks for the explanation, @amoffat!

**Pull request merged**
