### PR TITLE
Redditbot with encrypted config file

### PR DESCRIPTION
**Pull request by mpnordland**
Hey everyone, this is a resubmit of my previous PR with a little more explanation.
According to this comment, https://github.com/chaosbot/Chaos/issues/180#issuecomment-303981270, the public key crypto system we have is insufficient for protecting plaintexts longer than 214 bytes. In order to properly protect the config file for this bot I have extended the existing encryption system with symmetric encryption that uses AES. This symmetric encryption system creates a key store and uses the existing public key crypto to encrypt and decrypt these keys as needed. When the redditbot starts, it will first load the config file's key from the key store and use it to decrypt the config file. It then runs and replies to any comments on the /r/chaosthebot subreddit containing the text "hey chaosbot" with "Hey <username>". See #492 for more details and discussion.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
#553

**Comment by Swizz** [comment]
A lot of work wiped out, I know that you feel bro :confused:

**Comment by kylerchin** [comment]
:+1:

**Review by haru02w — APPROVED** [review]

**Review by eamanu — APPROVED** [review]

**Comment by mpnordland** [comment]
So I forgot about this thing entirely. I barely remember writing this code and I'm pretty sure this project is dead so I'm closing this PR.

**Pull request closed without merging**
