### PR TITLE
 A Declaration of the Independence of Cyberspace.

### PR DESCRIPTION
**Pull request by kylerchin**

### CODE REVIEW

**Comment by kylerchin** [comment]
:+1: :+1: :heart: :two_hearts: :blue_heart: :purple_heart: :green_heart: :yellow_heart: :heartpulse: :sparkling_heart: :tada: :heart_eyes: :grin: :grinning: :joy: :laughing: :smile: :smiley: :smiling_imp: :ok_hand: :fire: :metal: :raised_hands: :100: :heavy_check_mark: :white_check_mark: :ballot_box_with_check: :accept: :congratulations:

**Comment by bobjoe27326** [comment]
:+1: Kinda cool.... Is this from the EFF?

**Comment by kylerchin** [comment]
@bobjoe27326 Yep! https://www.eff.org/cyberspace-independence.
Also used for the Decentraland Project.

**Comment by kylerchin** [comment]
Imagine if Chaos bot replaced all management for all projects..... LOL...
Linux, Xorg, all GNU/Linux programs... Alll open source projects...
HOLY CODE..... The world would literately be Chaos. Financial Systems would collapse, Every satellite would crash, Linux crock-pots would not cook food.
It would be Chaos....

**Comment by kylerchin** [comment]
OMG.... Goverments running on Chaos....

**Comment by ethicalhacker-137** [comment]
:+1:

**Comment by ethicalhacker-137** [comment]
:100: :+1:

**Comment by kylerchin** [comment]
Ugg... .really need to change logo... something a bit more crazy.

**Comment by edpz** [comment]
👍

**Review by rudehn — APPROVED** [review]

**Pull request merged**
