### PR TITLE
webserver fixes and cleanups

### PR DESCRIPTION
**Pull request by amoffat**
Seems like the actual webserver was only ever listening on 8080 #187.  Made that 80.  Removed some code that wasn't really working / working correctly

### CODE REVIEW

**Comment by PlasmaPower** [comment]
If we're removing the fortune serving code, we should probably also remove the fortunes file.

**Comment by aksrum** [comment]
#163 changed port to 8080 for nginx proxy

**Comment by amoffat** [comment]
@aksrum interesting.  It must never have worked.  @g19fanatic I don't know puppet yet, are you able to look at this error log and see where things stopped working, if they indeed stopped working http://chaosthebot.com:8081/chaos-stdout.log

**Comment by amoffat** [comment]
Making this WIP in the meantime

**Comment by aksrum** [comment]
@amoffat This could indicate a problem... [http://chaosthebot.com:8081/chaos-stderr.log](http://chaosthebot.com:8081/chaos-stderr.log)

> Error: Could not install module 'puppetlabs-nginx' (latest)

**Comment by g19fanatic** [comment]
This is the issue. I will take a look at it in a few hrs. Hence the reason
I originally wanted to pull the modules into the repo, to keep dependencies
all within the project.

It should be easily fixable

**Comment by amoffat** [comment]
updated PR to just:

* remove fortune server
* remove "restart everything if webserver is down" code which weirdly locks up the entire server sometimes
* make webserver multithreaded

this should hold us over i think (and keep things from freezing up) until @g19fanatic's puppet changes land

**Pull request merged**
