### PR TITLE
Lower threshold per watchers from 0.05 to 0.04

### PR DESCRIPTION
**Pull request by PlasmaPower**
Right now it's at `6.5`, this would lower it to `5.2`.

### CODE REVIEW

**Comment by phil-r** [comment]
👍 Yeah it's a bit too high

**Comment by rhengles** [comment]
oh god no

**Comment by PlasmaPower** [comment]
@rhengles Why not? It's a slight change, and it feels like barely anything gets passed now.

**Comment by rudehn** [comment]
It's also the weekend. That might have something to do with it

**Comment by PlasmaPower** [comment]
@rudehn Good point.

**Comment by mark-i-m** [comment]
I'm not sure that changing the threshold value is the right solution. The threshold will keep needing to be being update as more or fewer people watch and depending on what day of the week. I would rather do something dynamic. For example, you must have more than half the votes of people who have historically voted on that day or some running average or something... These are just ideas, I don't know if any would work...

**Comment by hongaar** [comment]
Yeah.. those were the days:

image

Maybe we can use a moving (weighted) average (i.e. over last week, with more recent days having a heavier weight) of [commit activity](https://developer.github.com/v3/repos/statistics/#get-the-last-year-of-commit-activity-data) or [unique visitors](https://developer.github.com/v3/repos/traffic/#views)?

**Pull request closed without merging**
