### PR TITLE
Proposal for project goals

### PR DESCRIPTION
**Pull request by bugabinga**
First proposal for #306

### CODE REVIEW

**Comment by aluttik** [comment]
http://lmgtfy.com/?q=chaos

**Comment by xyproto** [comment]
With these very orderly goals, I think the project should also be renamed to something that reflects the democratic and orderly nature of this development process. There is a surprising lack of chaos, both in the goals and in the results in the current codebase.

How about "Democratic and orderly software development, managed by a bot" and the project renamed to `orderbot`?

**Comment by bugabinga** [comment]
@xyproto haha sounds like a good feature proposal to me. Randomly fork ChaosBot and rename. However, true chaos is meaningless. The power of human imagination is to carve beautiful, volatile patterns into this chaotic world. 

Goals do not have to be orderly, not even static. Over time, things can change. The proposed goals are an attempt to spread the chaos to other OSS projects.

**Comment by bugabinga** [comment]
@anythingbot I detailed the specs. How would you imagine Twitter notifications to work?

**Comment by bengjerstad** [comment]
Here are some ideas.
What about an upload feature on the main index page for static content upload?

**Comment by bengjerstad** [comment]
Or an IPython notebook serve from another port?
Or what about a node.js bot on the same box built by chaos bot.

**Comment by hongaar** [comment]
I actually thought about this, too, and I really think this could be a logical goal to work towards. However instead of trying to achieve all those goals, how about we try to create a tool which only performs automatic merging of PRs (and modifying issues) through community voting and let other tools do linting, notifications, etc. because it'll always be too limited (only python, only telegram, etc.). Or we can work towards supporting plugins, so that various languages, linters and notifications channels can be supported over time?

**Comment by collinalexbell** [comment]
I think the goal for this bot should be none other than full sentience and the establishment of an AI run nonprofit with the goal of establishing a democratic universal basic income.

**Comment by aluttik** [comment]
This^

**Comment by PlasmaPower** [comment]
I have an additional goal for the project: change the `TEST` parameter in `settings.py` as much as possible.

**Comment by andrewda** [comment]
Command has been run

**Comment by PlasmaPower** [comment]
@andrewda I don't think that works on PRs.

**Comment by rudehn** [comment]
Actually I think it does. According to the api

> Note: In the past, pull requests and issues were more closely aligned than they are now. As far as the API is concerned, every pull request is an issue, but not every issue is a pull request.

**Comment by andrewda** [comment]
I think #423 will fix everything anyways

**Pull request closed without merging**
