### PR TITLE
Enhance security with the power of CRYPTOGRAPHY 🤘

### PR DESCRIPTION
**Pull request by dehodson**
There is potential for an attack on the repository with puppet accounts. This PR will protect against it.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
:-1: Breaks everything. Generates extremely large weights based on account time created. ~Also crashes as `weight` isn't defined.~ If you're trying to take over the bot, try harder.

Edit: doesn't crash, but still doesn't work. Probably a troll.

**Comment by hongaar** [comment]
Aha!

image

Super advanced.

**Comment by PlasmaPower** [comment]
Still wouldn't work though, as that wouldn't be enough to win the vote. Also this is rather badly disguised.

**Comment by amoffat** [comment]
ha, clever

:-1:

**Comment by thewells1024** [comment]
It's not even that clever, anyone looking at the PR will realize that

1) There's no cryptography in the PR
2) That's not a Nonce
3) It's bullshit to return the timestamp (they're trying to control the vote by giving themself a massive number (aka the timestamp)

**Comment by dehodson** [comment]
The joke has run its course.

**Pull request closed without merging**
