### PR TITLE
API key encryption module

### PR DESCRIPTION
**Pull request by sugar700**
This will allow decrypting stuff like API keys without anyone knowing the API key (other than the person who uploaded those). Depends on secrecy of /etc/privkey.

### CODE REVIEW

**Comment by amoffat** [comment]
very clever! :+1:

**Comment by PlasmaPower** [comment]
Was just about to create this myself. :+1:

**Comment by scaule** [comment]
It's a very good Idea, i update #85 with that when pr is accepted

**Comment by PlasmaPower** [comment]
@scaule You might just want to make a new PR. It's hard to get revisions passed.

**Comment by scaule** [comment]
For the moment my PR is ok with credentials in etc .When this PR is accepted, i will create a new PR to use encryption.

**Comment by PlasmaPower** [comment]
@scaule sounds good.

**Comment by sugar700** [comment]
Anyway, gotta go, figure out yourself how to encrypt with encryption Python module. (hint: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#encryption)

Decryption is just means of calling decrypt method with binary string, you will get binary string back, but only on chaosbot computer (if you get pubkey.txt from it).

**Pull request closed without merging**
