### PR TITLE
Add fortune server on port 8080

### PR DESCRIPTION
**Pull request by the6p4c**
Serves Linux `fortune` fortunes.

### CODE REVIEW

**Comment by agargiulo** [comment]
Change issue title to have port 8080 not 80 as per your commit?

**Comment by amoffat** [comment]
i believe this PR is going to suffer from a similar issue described here #26 where your votes will be lost after merging/rebasing with upstream, due to chaosbot only counting votes made *after* the most recent changes

**Comment by the6p4c** [comment]
Whoops, didn't mean to have 8080 in the code - a vestige from testing. But I think we should go with that, as I think everyone's gonna want their little thing on 80. 8080's the next best thing.

**Review by callummr — APPROVED** [review]

**Comment by peatnik** [comment]
When will the bot restart now that this PR is merged?

**Pull request merged**
