### PR TITLE
Link the domain name

### PR DESCRIPTION
**Pull request by sugar700**

### CODE REVIEW

**Comment by Redmega** [comment]
:-1: Duplicate

**Comment by rhengles** [comment]
Duplicate of what?

**Comment by sugar700** [comment]
https://github.com/chaosbot/chaos/pull/8

**Comment by hank-der-hafenarbeiter** [comment]
#8 will never get merged though since it's votes have been voided ages ago...

**Comment by ndbroadbent** [comment]
Yeah, this one should be merged, and #8 should be closed because it has a merge conflict. It also has a crazy title.

**Comment by hongaar** [comment]
Would be nice if we have something like proposed in #30 so it's clear to everybody what the chances of a PR being merged are.

**Comment by robinduckett** [comment]
:+1:

**Comment by wolfgang42** [comment]
See also #76 to have it linked in the repository description.

**Review by kaezarrex — APPROVED** [review]

**Pull request merged**
