### PR TITLE
Fix sorting order for auto-closing stale issues

### PR DESCRIPTION
**Pull request by mark-i-m**
I promise, it's actually fixed this time (I hope)

### CODE REVIEW

**Comment by mark-i-m** [comment]
@PlasmaPower Meritocracy?

**Review by PlasmaPower — APPROVED** [review]

**Review by yet-another-account — APPROVED** [review]

**Comment by mark-i-m** [comment]
@phil-r @rhengles @eukaryote31 
Hmm... interestingly, it doesn't look like the :smile: reaction is counting as a positive vote

**Comment by mark-i-m** [comment]
@PlasmaPower you never voted

**Comment by PlasmaPower** [comment]
Oops done.

**Comment by mark-i-m** [comment]
@phil-r @rhengles @eukaryote31 @Ayyko Could you revote using :+1:... the smiley face doesn't appear to work...

**Comment by Ayyko** [comment]
#445 😆 
.... wrong emoji
😄 and 😃 now too

**Comment by mark-i-m** [comment]
Lol, @Ayyko, you still haven't voted :rofl:

**Comment by Ayyko** [comment]
:thinking: http://ayyko.xyz/ekeqlu.png

**Comment by mark-i-m** [comment]
Ah, thanks :+1: 
Browser caching ...

**Pull request merged**
