### PR TITLE
Voting threshold too high due to misleading github api

### PR DESCRIPTION
**Pull request by amoffat**
Could use a push to get this over the 14 vote threshold.  But then the threshold should be down to 3.54

### CODE REVIEW

**Review by pchauncey — APPROVED** [review]

**Comment by dehodson** [comment]
:100: Was in the middle of writing a similar change. Kudos.

**Review by Jac21 — APPROVED** [review]

**Comment by hongaar** [comment]
I feel that 14.4 is a bit too high, but 3.54 is way too low and easy. Take this PR as an example: only 15 minutes old and already 11 👍 . So the bar could be easily raised! Clickbait PR titles FTW!

Although on the other hand ...   chaos ...

**Comment by amoffat** [comment]
@hongaar definitely a balancing act

**Comment by hongaar** [comment]
Machine learning?

**Comment by rudehn** [comment]
I would bump the percentage to 5%. That would require 6 votes. Not too low but not too high either

**Comment by amoffat** [comment]
@rudehn sounds good.  let's do it in a new PR after this one lands, just so I don't reset the voting window

**Comment by hongaar** [comment]
I think the threshold as it's implemented now (minimum difference between + and -) should be set to 1 again, and instead there should be a minimum amount of votes needed (which could also be called a threshold confusingly and again could be based on stargazers, followers, whatever). That's truer to democracy I think.

**Comment by phil-r** [comment]
Something went wrong:
image

**Comment by dehodson** [comment]
At the Chaos project, we have very high standards.

**Comment by phil-r** [comment]
Everything is fine now 😌 
image

**Comment by viktorsec** [comment]
haha, hi @phil-r

**Comment by phil-r** [comment]
hi @viktorsec 👋

**Pull request merged**
