### PR TITLE
Ignore me please

### PR DESCRIPTION
**Pull request by hongaar**
Also include ignores from https://github.com/chaosbot/Chaos/pull/203

### CODE REVIEW

**Comment by yet-another-account** [comment]
What's the point of double ignoring the github secret?

**Comment by reddraggone9** [comment]
> Also include ignores from #203

#203 has been updated several times to resolve conflicts. Why are you trying to create more conflicts?

**Comment by reddraggone9** [comment]
screenshot from 2017-05-26 12-36-42

I am a prophet.

**Comment by hongaar** [comment]
@reddraggone9 #203 tries to do several things, so chances of getting conflicts are higher than for PRs changing only a single thing.

**Pull request closed without merging**
