### PR TITLE
Added X-Clacks-Overhead

### PR DESCRIPTION
**Pull request by viktorsec**

### CODE REVIEW

**Comment by Redmega** [comment]
GNU TERRY PRATCHETT

**Comment by viktorsec** [comment]
@paris-ci http://www.gnuterrypratchett.com/

**Comment by pchauncey** [comment]
I support this overhead

**Comment by hongaar** [comment]
This should be implemented using proper headers!

> **NOTE:**
> Page headers are, by design, sent before the page content is. Using this meta tag will NOT trigger Clacks-Overhead recognition on any of the various browser plug-ins as it is sent AFTER the page headers have already been sent (and therefore cannot be modified). This should be the last resort if you have absolutely no other option to configure your webserver's page headers.

**Review by hongaar — CHANGES_REQUESTED** [review]
This should be implemented using proper headers!

> **NOTE:**
> Page headers are, by design, sent before the page content is. Using this meta tag will NOT trigger Clacks-Overhead recognition on any of the various browser plug-ins as it is sent AFTER the page headers have already been sent (and therefore cannot be modified). This should be the last resort if you have absolutely no other option to configure your webserver's page headers.

**Pull request merged**
