### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by EtherTyper**
Add a code of conduct.

### CODE REVIEW

**Comment by Redmega** [comment]
Who enforces it?

**Comment by akilegaspi** [comment]
@Redmega The community I suppose

**Comment by aelse** [comment]
> Examples of unacceptable behavior by participants include:
> * The use of sexualized language or imagery and unwelcome sexual attention or advances
> * Trolling, insulting/derogatory comments, and personal or political attacks
> * Public or private harassment
> * Publishing others' private information, such as a physical or electronic address, without explicit permission
> * Other conduct which could reasonably be considered inappropriate in a professional setting

I think these rules are antithetical to the purpose of the project as a social experiment. I mean, going the utopian direction is one possible outcome of the experiment, but instead if this turns into a bot that superimposes penises on photos of unpopular politicians and tags them on twitter (just as an example) that might also be interesting.

**Comment by mrhwick** [comment]
Unless a code of conduct can be encoded in such a manner that ChaosBot can enforce the code itself, I feel like this doesn't really contribute to the experiment very much.

**Pull request closed without merging**
