### PR TITLE
Encryption, take 2

### PR DESCRIPTION
**Pull request by sugar700**
See #105. Merge error.

### CODE REVIEW

**Comment by lukeramsden** [comment]
Maybe try again? @serhalp seems to be downvoting with no good reason.

**Comment by viktorsec** [comment]
@lukeramsden it failed because of #138 

We are no longer able to influence merging by votes.

**Comment by lukeramsden** [comment]
@viktorsec Ahh I forgot about that :P

**Comment by amoffat** [comment]
@xfix re-open when you get a chance, this is a great feature

**Comment by PlasmaPower** [comment]
It's a shame I didn't see this, would have upvoted it (while dictator).

**Pull request closed without merging**
