### PR TITLE
add UptimeRobot badge

### PR DESCRIPTION
**Pull request by davidak**
With the badge you see directly in the Readme if the site is up and worth visiting.

It's also a link to uptime statistics so we will see how long the site will be offline.

Checks are executed every 5 Minutes. (free plan)

PS: This is my first PR here 🎉

### CODE REVIEW

**Review by andrewda — APPROVED** [review]

**Review by phil-r — APPROVED** [review]
Cool!

**Comment by Ayyko** [comment]
:+1: maybe add longest uptimes to the readme?

**Comment by phil-r** [comment]
And longest downtimes :trollface:

**Comment by davidak** [comment]
@Ayyko sure, why not.

I just created the check, so not much data right now.

We could also add a badge with uptime as %, but i'm not sure if that is helpful or clutter.

Just create another PR after this.

**Pull request merged**
