### PR TITLE
Embedded IRC Server ( powered by miniircd )

### PR DESCRIPTION
**Pull request by OpenNingia**
Because #54!

### CODE REVIEW

**Comment by amoffat** [comment]
there's also a [gitter](https://gitter.im/chaosthebot/Lobby) room open right now

**Comment by albino** [comment]
it's a lot more fun to write your own irc server though 👍

**Comment by Sag0Sag0** [comment]
If this passes ill work on making an irc bot to help with debugging.

**Comment by OpenNingia** [comment]
More fun indeed! :smile:

**Comment by ghost** [comment]
:(

**Comment by rudehn** [comment]
Probably because our benevolent leader didn't vote for it. Try opening a new PR

**Pull request closed without merging**
