### PR TITLE
Change voting window to 24 hours

### PR DESCRIPTION
**Pull request by golergka**
As per #18

### CODE REVIEW

**Comment by hxjuneja** [comment]
We need a better solution here, 24 hours will be too much as we will have more contributors

**Comment by golergka** [comment]
As we will have more contributors, we will have more contributors from different time-zones. Have you ever played on MMO server where majority of population were from the other part of the globe and everything interesting happens in the early morning hours? It's not that fun.

**Comment by dskoda1** [comment]
What exactly is wrong with 24 hours? If people are contributing from different time zones across the world this gives everyone a chance to vote on it, can someone that down voted please provide a counter argument?

@hardikj if we have more contributors don't we want to allow everyone to cast their vote? Not limit the # of votes by having it be a couple hours

**Comment by bperson** [comment]
You could also have value in dealing with the chaos left by the "previous timezone" :) + while the project has steam, there is value in having it move fast.

**Comment by OpenNingia** [comment]
24hours is too slow, and could lead the project into starvation. Let's say you need to rebase your pull request, do you need to wait an additional 24 hours to get it merged?

**Comment by hxjuneja** [comment]
@dskoda1 as I said, 24 hours is too much. In my opinion, we can do better, something on lines of having a dynamic window based on factors like 
- Amount of upvotes vs amount of downvotes since the initiation of the pull request (so if a pull request already have 100 upvotes vs 1 downvotes why wait 24 hours?)
- we can also consider the voting in previous timezones.

**Comment by psykzz** [comment]
We should have every 3 hours. Having a time where you wake up and having the bot be EU dominated vs US dominated adds to the fun. Alot can happen in 24 hours, 3 hours at least you can see your results the same day and will keep people interested.

**Comment by demonspork** [comment]
could we calculate the voting window based on a combination of number of votes and size of the PR? Like, if I make a very large PR it starts the timer at 24 hours. If we get a large number of votes, it drops the timer down for each threshold of votes to a minimum of 3 hours?

**Pull request closed without merging**
