### PR TITLE
Implement temporary error page

### LINKED ISSUE #365: Thematic 404 page 🎭
There's a lack of pages on the site, but does that mean we deserve a default 404 page?

### PR DESCRIPTION
**Pull request by mdcfe**
Should suffice until we get an actual request handler (if we even get a proper request handler). Closes #365.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Will this also apply for `404`s? Is any other error possible?

**Comment by mdcfe** [comment]
@PlasmaPower This applies to all errors, including 404s. I haven't used any Python web frameworks for quite a while, so I didn't want to just go and add one without everyone's approval.

~~If it's possible to override the `SimpleHTTPRequestListener.send_error` function then that would work better, but I'm not quite sure how that would work.~~ See below.

**Comment by mdcfe** [comment]
Correction: after looking through the `send_error` function, we can use `code`, `message` and `explain`. I'll add those to the page now.

**Review by o3LL — APPROVED** [review]

**Comment by mdcfe** [comment]
@PlasmaPower This should now substitute in any errors with their status code, message and explanation.

Example:
chrome_2017-05-31_22-35-40

**Review by PlasmaPower — APPROVED** [review]

**Review by RyanZim — APPROVED** [review]

**Comment by hongaar** [comment]
@md678685 

image

Bug or feature?

**Comment by mdcfe** [comment]
@hongaar Just went to see what happens in production before I saw your comment - it worked fine locally with Python 3.6.1, not quite sure what happened there 😆

**Comment by mdcfe** [comment]
Turns out using Vagrant installs Python 3.4. In 3.5 `%(code)s` changed, and the production environment runs 3.6. Going to make a PR to fix Vagrant, and a separate one to fix the error.

**Pull request merged**
