### PR TITLE
Retry on 202 status code

### LINKED ISSUE #432: Meritocracy list bug ?
-> https://github.com/chaosbot/Chaos/pull/425#issuecomment-305189271

### PR DESCRIPTION
**Pull request by andrewda**
Fixes #432 

_(probably)_

### CODE REVIEW

**Comment by rudehn** [comment]
What about the response data? Looks like you're just dropping it

**Comment by andrewda** [comment]
Just tested and it's working as advertised. Un-WIPing.

**Comment by PlasmaPower** [comment]
@rudehn On a 202 the response data should be empty or not important.

**Comment by rudehn** [comment]
Right, but after we wait and requery, the result was never returned. The requery is not guaranteed to be a 202.

**Comment by andrewda** [comment]
Yea that was a typo - should be working properly now.

**Review by PlasmaPower — APPROVED** [review]

**Pull request merged**
