### PR TITLE
Creating a "stats page" on http.

### PR DESCRIPTION
**Pull request by hank-der-hafenarbeiter**
start of a flask to show some stats on http.

### CODE REVIEW

**Comment by amoffat** [comment]
webservers everywhere

:+1:

**Comment by ghost** [comment]
consider using a simpler httpd and static pages instead?

maybe use stagit? http://git.2f30.org/stagit/log.html

**Comment by hank-der-hafenarbeiter** [comment]
I avoided httpd because i wouldn't want to deal with having to kill my processes if/when the bot dies/restarts. In my opinion this approach is easier because the sever is killed when the script stops. The server in the server file uses httpd and solved it with the application name. maybe that is a better approach.

**Comment by ghost** [comment]
Agreed, using external tools would lead to an unmaintanable project.
I guess it leaves us with to choices:
Don't use any external tools or use something like ansible to manage everything.

**Review by xylix — APPROVED** [review]

**Comment by hank-der-hafenarbeiter** [comment]
I think it makes more sense to do one http server for everything and since the other server is already up and running i'm retracting this PR.

**Pull request closed without merging**
