### PR TITLE
fix Patchset from requests

### PR DESCRIPTION
**Pull request by Swizz**
Getting patch raise no error but was in fact empty.

### CODE REVIEW

**Review by PlasmaPower — APPROVED** [review]
I looked through the code, and I don't think the return change will break anything.

**Comment by Swizz** [comment]
@PlasmaPower This was introduced here https://github.com/chaosbot/Chaos/commit/5a2d401c22361d72922085cb25c2d4748a627c6c for hotfix purpose, no more use in code.

**Comment by andrewda** [comment]
There are some bugs in chaosbot's review needed comments ;)

**Comment by PlasmaPower** [comment]
@andrewda Yep, fixed in #500

**Pull request merged**
