### PR TITLE
Fix rescinding reviews

### PR DESCRIPTION
**Pull request by PlasmaPower**
Previously, getting reviews would only return positive reviews. That's a problem! As noticed in #475.

### CODE REVIEW

**Review by mark-i-m — APPROVED** [review]

**Comment by PlasmaPower** [comment]
Meritocracy review? @mark-i-m looks like you're barely not in the meritocracy :slightly_frowning_face:

**Comment by mark-i-m** [comment]
Yep, I noticed that too... I get all the fun, no responsibilities :laughing:

**Review by andrewda — APPROVED** [review]

**Review by andrewda — APPROVED** [review]

**Comment by andrewda** [comment]
Uhh the bot's on an hour long cooldown right now...

**Comment by PlasmaPower** [comment]
I'm assuming you mean API cooldown. How often does the API limit refresh? Could we ask GitHub for extra requests?

**Comment by andrewda** [comment]
Oh I see the issue – GitHub gave us a completely inaccurate reset time so it calculated the cooldowns wrong. Then GitHub told us we actually had 1 hour until the next reset so the bot has 18 requests left for the next 50 minutes.

**Comment by andrewda** [comment]
Yea we could probably ask GitHub for a higher limit. I'm guessing they'll be pretty lenient as we haven't spammed the API and are pretty responsible with our API cooldowns.

**Comment by hongaar** [comment]
@andrewda @PlasmaPower I was thinking about this yesterday. I think when we ask GH for more requests, they might ask us to implement [conditional requests](https://developer.github.com/v3/#conditional-requests) first. We might want to simply mirror the entire issue/pr list into our own DB, which should be much faster and durable. We could roll our own, or use [gousiosg/github-mirror](https://github.com/gousiosg/github-mirror) or [piwik/github-issues-mirror](https://github.com/piwik/github-issues-mirror) (unmaintained).

**Pull request merged**
