### PR TITLE
fix invalid syntax

### PR DESCRIPTION
**Pull request by rudehn**
This is invalid syntax and is causing a revert of all new PRs. Fixing this should allow all new PRs to no longer be reverted.

### CODE REVIEW

**Comment by Ayyko** [comment]
https://www.python.org/dev/peps/pep-3107/#return-values 
What is getting mad about this?

**Comment by rudehn** [comment]
```
SyntaxError: invalid syntax
  File "./lib/db.py", line 23
    def create_adapter(adapter_name, config) -> AbstractAdapter:
                                             ^
SyntaxError: invalid syntax
```

```
File "./lib/db_adapters/interface.py", line 7
    class AbstractAdapter(object, metaclass=abc.ABCMeta):
                                           ^
SyntaxError: invalid syntax
```

If it doesn't like it, it doesn't like it

**Comment by mdcfe** [comment]
```
$ flake8
./lib/db.py:7:1: F401 'lib.db_adapters.interface.AbstractAdapter' imported but unused
```

**Comment by Ayyko** [comment]
¯\\\_(ツ)_/¯ fair enough

**Review by PlasmaPower — APPROVED** [review]

**Pull request merged**
