### PR TITLE
Tune netdata logs

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by reddraggone9** [comment]
Care to explain to the unenlightened?

**Comment by phil-r** [comment]
I think it's a followup to #260, but @ad-m probably can enlighten us ;)

**Comment by ad-m** [comment]
@reddraggone9 , Change brings peace in the world, universal love and ends all wars. This is the best possible change, so you should give it a positive vote. 

I want to debug netdata installation. I also think we have to publish startup.sh logs.

**Comment by reddraggone9** [comment]
I was looking for something more along the lines of:

As documented [here](http://docs.ansible.com/ansible/file_module.html), this will create a symlink at `/var/log/supervisor/x` that points to `/etc/`. I'm doing this so we can view the logs at http://chaosthebot.com:8081/

To which I would reply:

👎 Because
1. `/etc/` has private files that shouldn't be published, such as the [GitHub secret](https://github.com/chaosbot/chaos/blob/150a5b658362ee4799772f0d727d13c066eabba8/settings.py#L19-L24).
2. `x` is a terribly undescriptive name.
3. This probably shouldn't be in `netdata.yml` since it's not Netdata specific.

**Comment by ad-m** [comment]
@reddraggone9 , why do not you want peace in the world?

**Comment by rhengles** [comment]
👎  This is an attack, pure and simple

**Pull request closed without merging**
