### PR TITLE
Revert "merging PR #471: Mention meritocracy when needed"

### PR DESCRIPTION
**Pull request by PlasmaPower**
This change was using the DB, which broke a lot of stuff. Reverting until the DB gets fixed.

@rudehn when you do the database redo PR, would you mind un-reverting this? Thanks.

### CODE REVIEW

**Comment by thedanish** [comment]
Meritocracy is a white invention by those with power and offensive to trans queer people of color.

:-1:

**Comment by mark-i-m** [comment]
@PlasmaPower What exactly did it break?

**Comment by PlasmaPower** [comment]
@mark-i-m look at the issues. Chaosbot is down right now. I'm not exactly sure what's happening, but all the tracebacks I've seen seem to be coming from the database code.

**Comment by PlasmaPower** [comment]
Looks like @amoffat got it working after all. Closing.

**Pull request closed without merging**
