### PR TITLE
inversed voting mechanism

### PR DESCRIPTION
**Pull request by larsnolden**
👎  => positive vote
👍 => negative vote

... chaos :)

### CODE REVIEW

**Comment by EtherTyper** [comment]
@larsnolden Even better: automatic acceptance

**Comment by hanspagel** [comment]
👍

**Comment by reddraggone9** [comment]
@EtherTyper We tried that in #48 (which got in on a technicality). It didn't seem like a terribly popular idea, but it was only reverted because it was buggy.

**Comment by 2dvisio** [comment]
👍

**Comment by qwerm** [comment]
So does that mean this has 27 downvotes or 27 upvotes?

**Pull request closed without merging**
