### PR TITLE
Adding some interaction part 2.

### PR DESCRIPTION
**Pull request by carsonRadtke**
Took advice from several people and this is what I got. Previous pr #242

### CODE REVIEW

**Review by xyproto — APPROVED** [review]

**Comment by xyproto** [comment]
Very nice effect! Could the background color be set to transparent, to more easily combine it with the varying present and future css styles?

**Comment by phil-r** [comment]
for those, who want to see it in action: https://jsfiddle.net/Phil/1e8Lc757/

**Comment by reddraggone9** [comment]
@phil-r The hero we *need*, but not the one we deserve.

**Comment by phil-r** [comment]
@reddraggone9 😊

**Comment by amoffat** [comment]
I just noticed this on the home page @carsonRadtke.  Amazing :clap: :clap: :clap:

**Pull request merged**
