### PR TITLE
Gave the GitHub ribbon a z-index to prevent it being covered by the c…

### PR DESCRIPTION
**Pull request by Jac21**
…urrent content

### CODE REVIEW

**Comment by Jac21** [comment]
Current state: 
image

**Comment by reddraggone9** [comment]
How about just moving the link to the bottom of the page before we start resorting to z-indices?

**Comment by Jac21** [comment]
Good point, but I've yet to see that ribbon used in that fashion, quite honestly.

**Comment by reddraggone9** [comment]
You do understand that I mean move the text which makes up the `<a>` element to the bottom of the HTML file, right? It would produce the same visual change on the rendered page as your change.

**Comment by Jac21** [comment]
_"You do understand"_

Apparently not, totally misunderstood your comment.

**Comment by reddraggone9** [comment]
@abrad1212 @Mike-Dunton If you downvoted because of the implementation, but liked the idea in general, you might want to take another look.

**Comment by Jac21** [comment]
Yes, please excuse my lack of foresight in simply just opening up the html itself.

**Pull request closed without merging**
