### PR TITLE
Get rid of the annoying extra whitespace in the middle of the message

### PR DESCRIPTION
**Pull request by mark-i-m**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Also fixed in #377

**Comment by mark-i-m** [comment]
Oh, may the best PR win :running_man:

**Comment by PlasmaPower** [comment]
@mark-i-m as #377 deprecates this, and appears to be successful by a wide margin, would you mind closing this? I say that only because the voting window is so unbearably long. I'd prefer to not have to wait it twice.

**Comment by PlasmaPower** [comment]
(the reason to close this PR not mine is because my PR contains your fixes, but your PR doesn't contain my changes)

**Comment by PlasmaPower** [comment]
Thanks! :heart:

**Comment by mark-i-m** [comment]
Np... the timer keeps getting reset on my 3 PRs anyway...

**Pull request closed without merging**
