### PR TITLE
Remove sexism

### PR DESCRIPTION
**Pull request by tbodt**

### CODE REVIEW

**Review by loops-and-spells — APPROVED** [review]

**Review by jblz — APPROVED** [review]
👍👍👍👍👍👍

**Review by MarkVaughn — APPROVED** [review]

**Comment by benharold** [comment]
👎🏽 for bad grammar. It should be 'his or hers' not 'their', as 'their' implies plurality.

**Comment by monsonjeremy** [comment]
👍

**Comment by ECrownofFire** [comment]
👍 I like being included.

**Comment by jblz** [comment]
> 👎🏽 for bad grammar. It should be 'his or hers' not 'their', as 'their' implies plurality.

Non-gender-specific singular `they` / `their` is perfectly acceptable.

https://en.wikipedia.org/wiki/Third-person_pronoun#Singular_they
https://en.wikipedia.org/wiki/Singular_they

**Pull request merged**
