### PR TITLE
PR comments

### PR DESCRIPTION
**Pull request by hongaar**
Leave a comment containing the vote summary on PR when it's merged or closed by @chaosbot.

Includes #148

Relevant commit: 582f20422244f1ea265b1d34bcc436deaa4a2da4

### CODE REVIEW

**Comment by hongaar** [comment]
Will look something like 

image

**Comment by rudehn** [comment]
This is super cool

**Comment by amoffat** [comment]
yeah great work @hongaar

**Comment by rudehn** [comment]
now will it update the status if it goes from failed to passing?

**Pull request merged**
