### PR TITLE
Make docker scripts current directory independent

### PR DESCRIPTION
**Pull request by PlasmaPower**
Instead of `cd dev/docker; sudo ./run.sh` this allows `sudo dev/docker/run.sh`.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
@e-beach Are you a bot? You seem to be upvoting PRs suspiciously fast and consistently, without watching the repository.

**Comment by amoffat** [comment]
Random question, why `sudo` when you launch the container?

**Comment by PlasmaPower** [comment]
@amoffat From [the Arch Linux wiki Docker page](https://wiki.archlinux.org/index.php/Docker):

> If you want to be able to run docker as a regular user, add yourself to the docker group.
>
> **Warning:** Anyone added to the docker group is root equivalent. More information [here](https://github.com/moby/moby/issues/9976) and [here](https://docs.docker.com/engine/security/security/).

**Comment by amoffat** [comment]
Aha, interesting

**Comment by PlasmaPower** [comment]
This PR also actually needs a meritocracy review.

@rudehn @chaosbot @rhengles @hongaar @ad-m @md678685 @xyproto @phil-r @PlasmaPower @eukaryote31 @Smittyvb @viktorsec @MUCHZER @andrewda @amoffat

**Review by andrewda — APPROVED** [review]

**Pull request merged**
