### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by lemontron**

### CODE REVIEW

**Comment by wolfgang42** [comment]
Is there a rationale behind this particular change? I'm really not sure what utility it provides.

**Comment by AliKarpuzoglu** [comment]
@wolfgang42 he's trying to advertise using this project

**Comment by stefannew** [comment]
It might be helpful, going forward, to also provide a PR description.

**Comment by lemontron** [comment]
The site chaos bot has up right now doesn't provide much utility so I thought I'd link a site with some utility bro bro bro

I think all websites should direct to hux.com personally, as it is best site bros

I say it should go through, lets GOO

**Pull request closed without merging**
