### PR TITLE
Make label issues methods more flexible

### PR DESCRIPTION
**Pull request by hongaar**

### CODE REVIEW

**Review by andrewda — APPROVED** [review]
Looks good!

**Review by phil-r — APPROVED** [review]
👍 LGTM 
P.S. Would be cool to have some tests

**Review by flibustier — APPROVED** [review]

**Comment by flibustier** [comment]
Shame!

**Comment by Swizz** [comment]
WTF ? Rejected with 17 pros and 0 cons ? Oo

**Comment by phil-r** [comment]
Not approved by meritocracy, I didn't want to approve it because I was a part of PR.

**Comment by flibustier** [comment]
This is how you start a revolution! Power to the people!!

**Comment by Swizz** [comment]
Shame on me. I based a bunch of ideas on it

**Comment by phil-r** [comment]
@hongaar Lets reopen ;)

**Pull request closed without merging**
