### PR TITLE
👨‍💻 Vagrant environment for local development.

### PR DESCRIPTION
**Pull request by patricknelson**
Vagrant local development environment. Running Ubuntu 14.04 (Trusty) with `python3`, automatically installing requirements and etc. My alternative to the `Dockerfile` request in #116 😄 

**NOTE:** To use this you will still need to manually initialize your github secrets under `/etc` or comment out code referencing github's API's.

See also: https://github.com/chaosbot/chaos/pull/107 (runs in this VM)

### CODE REVIEW

**Comment by patricknelson** [comment]
Need to drop in documentation, don't vote yet...

**Comment by patricknelson** [comment]
Ok done 😄

**Comment by drsirmrpresidentfathercharles** [comment]
👍

**Comment by mrhwick** [comment]
For future reference (for now, anyways), you can use "WIP" in the title of your PR's to indicate that they are not ready to have votes counted.

**Comment by phil-r** [comment]
@patricknelson Hi, I tried to run it, and it installed python3.4, and it looks like nothing works with it, Any ideas what went wrong? Or something is completely wrong with my setup?

**Comment by patricknelson** [comment]
@phil-r you'll have to provide more specifics. Also a few things:

1. I'm not a python dev
2. I've provided the most detail I can to help per my initial "NOTE" above (https://github.com/chaosbot/chaos/pull/123#issue-230888856) since I expect it to fail to run properly with the code as-is, this only gets you up and running with a basic VM.

That's also not to mention with how "chaotic" the codebase is, since it could constantly change at any time. If you can't get it  to work, it really could be for any reason and will require some head-scratching to figure out. Sorry.

**Comment by phil-r** [comment]
@patricknelson haha, fair enough ;) btw I've managed to run everything without vagrant, so it's fine for now

**Comment by patricknelson** [comment]
Great! How did you work around (or with) the tight binding to the github API? Did you just plug in your own secrets and use your own repo's and etc?

**Comment by phil-r** [comment]
@patricknelson Yeah, In the end I did the following
- forked repo
- changed `GITHUB_USER` to my username
- created new secret in https://github.com/settings/tokens and added it to `/etc/github_pat.secret`
- installed python3 on my computer (with `brew install python3`)
- installed dependencies with `pip3 install -r requirements.txt`
- run with `python3 chaos.py`
`¯\_(ツ)_/¯`

**Pull request merged**
