### PR TITLE
Fix voters.json logic (broken by #377)

### PR DESCRIPTION
**Pull request by PlasmaPower**
I misplaced some overwriting stuff. @amoffat when you merge this PR, would you mind clearing up `voters.json`? It currently contains 2 copies of the data.

If someone could double check the new logic that'd be great.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Copy of the correct `voters.json` in case it gets corrupted further: https://gist.github.com/12ba5358b521dc7b03df65259dd4f23f

**Comment by hongaar** [comment]
@PlasmaPower data is [corrupted anyway](https://github.com/chaosbot/Chaos/pull/391#issuecomment-304886817) 😄

**Comment by PlasmaPower** [comment]
@hongaar Yeah I'm hoping amoffat can fix that when they merge this.

**Comment by rudehn** [comment]
```
with open("voters.json", 'r') as f:
    total_votes = json.load(f)

with open("voters.json", 'w') as f:
    json.dump(total_votes, f)
```

Does this not work for you? You have to open the file in two different modes but you don't have to worry about file pointers and files are closed automatically.

**Comment by PlasmaPower** [comment]
@rudehn I think that doesn't work if the file doesn't already exist.

**Comment by amoffat** [comment]
@PlasmaPower ok I think we're back.  This is merged and voters.json cleaned up.  Good work :+1: 

You'll need to close this PR manually...github not detecting the squash commit on master

**Comment by PlasmaPower** [comment]
Great!

**Pull request closed without merging**
