### PR TITLE
Add a "secret" terminal to the page

### PR DESCRIPTION
**Pull request by mdcfe**
Currently it's just a base for people to build off, but if someone implemented JSON-RPC or some more routes on the server side, we could have a neat way to access data from the server through this.

### CODE REVIEW

**Comment by mdcfe** [comment]
Failing due to #389, not me.

**Comment by rhengles** [comment]
I would approve this in a separate page, specially because it's not functional yet. It's adding dependencies on the home page, so for now it's 👎

**Comment by o3LL** [comment]
3 libs for 1 funny moment 👎 
Do it from scratch 🗡

**Comment by hongaar** [comment]
Frontend is mainly fun play and chaos anyway, so sure why not! 👍

**Comment by mdcfe** [comment]
@rhengles The libraries are now loaded the first time the word "experiment" is clicked rather than immediately on page load, so it won't be loaded if you don't want to use it.

**Review by hongaar — APPROVED** [review]

**Review by o3LL — APPROVED** [review]

**Comment by rhengles** [comment]
I would really rather have this on a separate page, but here's my upvote 👍  This can be improved later.

**Pull request merged**
