### PR TITLE
Replaced oligarchy with anarchism. Smash the /bin/bash

### PR DESCRIPTION
**Pull request by ghost**
Power to the pull requests!

### CODE REVIEW

**Comment by rtzoeller** [comment]
👎

**Comment by dragbone** [comment]
👎

**Comment by ghost** [comment]
As I expected, nothing but boring sheeple in this repo

**Comment by sosodev** [comment]
👍

**Comment by nxmq** [comment]
👎

**Comment by eighthjouster** [comment]
👎

**Comment by izik1** [comment]
Not even current tense :-1:

**Comment by petitJAM** [comment]
:+1:

**Comment by ghost** [comment]
@izik1 Why are you insisting on present tense? Because someone told you to? Present tense is passé. Don't be a conformist.

**Comment by izik1** [comment]
@vkgfx because I wanted to actually, and doing a semi sarcastic comment hardly counts as insisting :p

**Pull request closed without merging**
