### PR TITLE
Bring back interaction

### PR DESCRIPTION
**Pull request by carsonRadtke**
Add an interactive canvas to the homepage

### CODE REVIEW

**Comment by ozyx** [comment]
Should be in its own `.js` file.

**Comment by Redmega** [comment]
I agree, you should move it to its own file.

**Comment by carsonRadtke** [comment]
Took the advice of @ozyx and @Redmega now there is a chaos.js file.

**Comment by reddraggone9** [comment]
That's better, but you should really move the script tag to the end of the body.

https://stackoverflow.com/questions/585272/content-script-img-outside-html-tags

**Comment by ozyx** [comment]
Open a new PR with @reddraggone9 changes implemented and I will upvote

**Pull request closed without merging**
