### PR TITLE
Make @Smittyvb the nominal monarch for a day (June 8, 2017)

### PR DESCRIPTION
**Pull request by mark-i-m**
@Smittyvb ^^^

### CODE REVIEW

**Comment by mark-i-m** [comment]
:warning: This PR does not have a positive meritocracy review.

Please review: @andrewda @PlasmaPower @xyproto @hongaar @eukaryote31 @phil-r @Leigende @rudehn @amoffat @ad-m @rhengles @Smittyvb @MUCHZER @chaosbot @md678685

**Comment by andrewda** [comment]
Hello @mark-i-m bot

**Review by andrewda — APPROVED** [review]

**Comment by PlasmaPower** [comment]
Is it a bot though? It's not on the @mark-i-m fork, and the meritocracy includes members from `voters.json` which @mark-i-m's docker instance likely does not have.

Edit: I've been bamboozled.

**Comment by mark-i-m** [comment]
Hello @andrewda, I detect that you are talking about me, so I will not post

**Comment by PlasmaPower** [comment]
I hate to break it to you @chaosbot, but you're being replaced by @mark-i-m

**Comment by andrewda** [comment]
@mark-i-m pretty sure you have to resubmit the PR – /vote reopen only works on issues.

**Comment by andrewda** [comment]
Nevermind I guess? I don't think it's ever been done a PR – interested to see how the bot will react...

**Comment by rudehn** [comment]
Well it recognizes the command, not sure if it will do anything meaningful though

**Comment by mark-i-m** [comment]
Hmmm... I opened number #521 anyway...

**Comment by mark-i-m** [comment]
Part of me wants to let them race and see what happens... probably a merge conflict.

**Comment by PlasmaPower** [comment]
I think it'd work, then result in an instant merge.

**Comment by andrewda** [comment]
Yea, that's my guess @PlasmaPower

**Comment by PlasmaPower** [comment]
This PR will win a race.

**Comment by mark-i-m** [comment]
Hmm... that would be interesting... Shall we allow it and see?

**Comment by mark-i-m** [comment]
Also, should we try to prevent that in the future?

**Comment by andrewda** [comment]
I don't see a real reason to prevent it, but maybe change the behavior so it restarts the vote timer. That would be better than opening a new PR in my opinion.

**Comment by rudehn** [comment]
I don't think this one will work.

**Comment by rudehn** [comment]
Looks like it did reopen after all.

**Comment by PlasmaPower** [comment]
Sneaky @rudehn, but will it work...? It might actually, I'll look through the code.

**Comment by rudehn** [comment]
It needs the meritocracy approval which I don't think you can get once it's closed.

**Comment by rudehn** [comment]
But it might be worth checking if there's a vulnerability here.

**Comment by PlasmaPower** [comment]
@rudehn yeah I'm pretty sure you can get a review. The rules are: positive, on PR, on most recent commit. All of those rules can be satisfied while the issue is closed. The PR previously failed because @mark-i-m pushed 0af978e3f78106647026f49169401f295b676b5b, which wasn't reviewed. As for the attack I thought you were executing, I think you'd need to wait for the chaosbot comment if you wanted to do that.

**Comment by PlasmaPower** [comment]
Never mind, looks like you can only post neutral reviews after the issue has been closed:

image

As you can see, it's missing the options for approve/comment/suggest changes.

**Pull request closed without merging**
