### PR TITLE
Reopen #443 according to #364 

### PR DESCRIPTION
**Pull request by eamanu**
Fix bugs

### CODE REVIEW

**Comment by mark-i-m** [comment]
Hmm... permissions errors on CI build

**Comment by mark-i-m** [comment]
Ah, I just saw #547

**Comment by PlasmaPower** [comment]
https://twitter.com/ChaobotsC/status/873593020997713920

**Comment by PlasmaPower** [comment]
If you'd like, I could fix the API tokens and encryption and everything, then resubmit. This isn't getting passed without proper handling of the tokens.

**Pull request closed without merging**
