### PR TITLE
Use requestAnimationFrame in chaos canvas on website

### PR DESCRIPTION
**Pull request by jakejdavis**
As recommended in #312 I have used requestAnimationFrame instead of setInterval which speeds up the canvas

### CODE REVIEW

**Comment by PlasmaPower** [comment]
The distance moved should be multiplied by the time delta.

Edit: as it is, it'll be dependent on framerate.

**Comment by jakejdavis** [comment]
@PlasmaPower sorry, I'm quite new to this project and javascript as a whole so I probably haven't done it right. You can make your own pull request doing the thing you have said if you want. I'll definitely upvote your PR to fix this issue.

**Comment by PlasmaPower** [comment]
@jakejdavis try this: https://gist.github.com/PlasmaPower/013445fa9d8bf25ffb68dafb61078bde

untested and I've gotta go

**Comment by phil-r** [comment]
@jakejdavis or this: https://jsfiddle.net/Phil/1e8Lc757/1/ 
P.S tested 😆

**Pull request merged**
