### PR TITLE
Voting is now more realistic

### PR DESCRIPTION
**Pull request by mgardne8**
Your vote may or may not count, you don't actually know, Just like in real democracies!!

### CODE REVIEW

**Comment by PlasmaPower** [comment]
:-1: We aim to be better than actual democracies, not to emulate them.

**Comment by PlasmaPower** [comment]
You know a PR is unpopular when the author upvotes it.

Edit: then changes it to :tada: after this comment.

**Comment by mgardne8** [comment]
Your dictatorship holds power no more sir, begone.

**Comment by PlasmaPower** [comment]
@mgardne8 My dictatorship doesn't, by choice. But my vote does, and my voice does.

**Comment by mgardne8** [comment]
MAYBE!

**Comment by PlasmaPower** [comment]
This PR also has the same problem as previous RNG PRs, where the RNG is recalculated every time the vote is tallied, in this case effectively nullifying it.

**Comment by mgardne8** [comment]
Yeah, we have a broken polling machine, you never know what you'll get, you might thing you're winning, get one more vote and then be horribly out of luck.

**Comment by PlasmaPower** [comment]
@mgardne8 Not how it works - do you know about the extended voting window?

**Pull request closed without merging**
