### PR TITLE
correct grammar

### PR DESCRIPTION
**Pull request by benharold**
"Their" implies plurality, while the subject is singular.

### CODE REVIEW

**Comment by EtherTyper** [comment]
@benharold https://en.wikipedia.org/wiki/Singular_they

**Comment by snood1205** [comment]
Furthermore, "his or her" assumes that everyone uses "his" or "her" but that's not accurate.

**Comment by benharold** [comment]
@EtherTyper I have no time to suffer ambiguity. I prefer the concrete.

**Comment by ECrownofFire** [comment]
What if the owner is multiple people working together?

**Comment by benharold** [comment]
@ECrownofFire I believe you mean "What if the owners are multiple people working together?"

**Comment by ECrownofFire** [comment]
"What if the owner is actually a group?" is perfectly valid.

Unless you prefer E-Prime, in which case it'd be "What if the owner instead consists of a group?"

**Pull request closed without merging**
