### PR TITLE
README.md: Added most ambitious possible goal.

### PR DESCRIPTION
**Pull request by collinalexbell**
["If something is important enough, you do it even if the odds aren't in your favor."](https://www.youtube.com/watch?v=JGfygJXTwq4)

### CODE REVIEW

**Comment by collinalexbell** [comment]
Everyone is talking about Democratic AI this Democratic AI that. 

This would be a real democratically run AI.

**Comment by rhengles** [comment]
👎 because of https://github.com/chaosbot/Chaos/issues/306#issuecomment-304700742

**Comment by rudehn** [comment]
7 hours left on this PR.. @hongaar perhaps your log function needs tweaked?

**Comment by mark-i-m** [comment]
Yeah, I was wondering about that for #318 too

**Comment by mark-i-m** [comment]
Which literally just got accepted :tada: ... but I suspect that the timer is off somehow...

**Comment by phil-r** [comment]
@mark-i-m I'm writing tests for some voting related things - the whole thing is a bit confusing

**Comment by hongaar** [comment]
@rudehn hmm looks like it. Will take a look tomorrow if it isn't fixed somewhere else by then!

**Pull request closed without merging**
