### PR TITLE
Add bonus to pull requests that are palindromic or 1337

### PR DESCRIPTION
**Pull request by benbarth**
A very rare bonus 👍. Everyone loves a boost!
If your pull request happens to be a palindrome or divisible by 1337 then your PR get a little 👍 boost.

### CODE REVIEW

**Comment by rhengles** [comment]
This would need to be documented on the commit messages and automatic PR comments. I would also add PRs divisible by 100 or 1000.

**Comment by hongaar** [comment]
Yay! Despite its name, chaosbot is not really chaotic yet. This slightly helps with that... :+1:

**Comment by benbarth** [comment]
Hey everyone,
If I added @rhengles's suggestion of documenting the bonus, would you find this feature more acceptable?

**Comment by benbarth** [comment]
Isn't it more chaotic if you secretly get a +1 boost?

**Comment by rudehn** [comment]
I really like the idea. Makes things more interesting

**Comment by PlasmaPower** [comment]
I don't mind randomness, but this adds a rush to some PR numbers.

**Comment by PlasmaPower** [comment]
And even with randomness, sometimes you need to recreate a PR to get the vote passed.

**Comment by rudehn** [comment]
How about after 'n' votes on a PR, chaosbot randomly assigns an additional +1/-1 vote?

**Comment by hongaar** [comment]
I'd like to see a random **merge now** trigger, where if certain pseudo-randomised conditions apply, a PR gets merged instantly. Would be fun.

**Comment by rudehn** [comment]
Any ideas on how to do it? I imagine somebody could submit many PRs for the same code in an attempt to hit the instant merge

**Comment by benbarth** [comment]
Oooo... Maybe if the PR hits a downvote threashold (-20) the PR *might* get pulled.

**Comment by reddraggone9** [comment]
@hongaar 

> random **merge now** [...] Would be fun.

Says the guy who doesn't have to change Chaos' diaper when it craps itself 😜

**Comment by hongaar** [comment]
@reddraggone9 oh you can give me ssh access to the server. Would be fun. 😁

**Comment by hongaar** [comment]
On a serious note though, it'd be definitely be wise to only do this after #112 somehow gets some work first, and preferably some syntax/compilation/unittest/etc checks..

**Comment by benbarth** [comment]
@hongaar Agreed.

**Pull request closed without merging**
