### PR TITLE
write all cout input to file so that it can be used in the server

### PR DESCRIPTION
**Pull request by hank-der-hafenarbeiter**
write everything from cout into a file so it can easily be used (on the http server for example)

### CODE REVIEW

**Comment by rudehn** [comment]
Why not just configure the logger to output to a file as well?

**Comment by hank-der-hafenarbeiter** [comment]
doesn't the logger output go to cout anyway? so it will should be routed to the file too.

**Comment by rudehn** [comment]
I think it's just cleaner to let the logger handle all program output. That's what its there for after all

**Comment by miller-time** [comment]
what's the reason for using the names "cout"/"cerr" instead of "stdout"/"stderr"?

**Comment by OpenNingia** [comment]
c++ oriented I guess

**Comment by hank-der-hafenarbeiter** [comment]
So now this PR only redirects the logger output to a file called cerr.txt in the directory of the script.

Why cerr? Logger writes to stderr which is cerr in c++ and i didn't really think that it made a difference. I don't know. It's what I've always been using.

**Comment by MCSH** [comment]
The logger should be enough for this, you dont need to reinvent the wheel.
👎

**Comment by hank-der-hafenarbeiter** [comment]
@MCSH look at the last commit. Redirecting the logger to somewhere useful is literally all it does. 2 Lines of code.

**Comment by MCSH** [comment]
In unix every program should be a [filter](https://en.m.wikipedia.org/wiki/Filter_(software)#Unix). 

>>> In Unix and Unix-like operating systems, a filter is a program that gets most of its data from its standard input (the main input stream) and writes its main results to its standard output (the main output stream). Auxiliary input may come from command line flags or configuration files, while auxiliary output may go to standard error. 

This is just bad practice.

**Pull request closed without merging**
