### PR TITLE
More PR labels

### PR DESCRIPTION
**Pull request by pchauncey**
This PR adds a couple labels to PRs:

- mergeable
- conflicts

### CODE REVIEW

**Comment by hongaar** [comment]
Could this be optimised so that we only add the label if it doesn't already have it?
(considering GH API rate limits might come into play at some point..?)

**Comment by amoffat** [comment]
@pchauncey do you prefer any specific colors for these labels?

**Comment by pchauncey** [comment]
@amoffat You pick!   Something "good" and something "bad"?

**Comment by pchauncey** [comment]
Nice, those are great.  Thanks!

**Comment by pchauncey** [comment]
@hongaar  I like the idea of optimizing, but I'm going to have to save that for another PR.  I need to figure out how to extract the labels from the `pr` object before or during relabel, etc.

**Comment by hongaar** [comment]
@pchauncey would this work?

```python
if "mergeable" not in list(map((lambda x: x["name"]), pr["labels"])):
    label_pr(api, urn, pr, "mergeable")
```

**Comment by phil-r** [comment]
This PR brought a lot of chaos =)

**Comment by reddraggone9** [comment]
As is only appropriate.

**Pull request merged**
