### PR TITLE
Docker Documentation update - troubleshooting area

### PR DESCRIPTION
**Pull request by g19fanatic**
to include some info w/ issues that might come from using a smaller VPS for development

Checkout #281

### CODE REVIEW

**Comment by reddraggone9** [comment]
self-upvote

Wat?

**Comment by g19fanatic** [comment]
@reddraggone9 I guess my vote is implicit when I do the PR?

Side-note, can I downvote my own PR if I decide I don't like it?
Does that just make it even or does it downvote?

**Comment by rudehn** [comment]
@g19fanatic you get 1 vote. PR owner automatically votes yes, but you can downvote to overrule yourself

**Comment by reddraggone9** [comment]
@g19fanatic 
screenshot from 2017-05-26 12-46-59
*modifies readme; doesn't actually read readme*

**Comment by reddraggone9** [comment]
@g19fanatic 

[This](https://github.com/chaosbot/Chaos/blob/d1cfad21414e019975c4a316faad20029b9afe07/github_api/voting.py#L34-L36) is the relevant code if you're interested.

**Comment by g19fanatic** [comment]
Yea... Boo

**Pull request closed without merging**
