### PR TITLE
I refuse to IGNORE this SETTING

### PR DESCRIPTION
**Pull request by jgrigonis**

### CODE REVIEW

**Comment by ashleysommer** [comment]
The setting is there to be ignored.
👎

**Comment by kdavis** [comment]
I disagree. The bot could become self-aware!
👎

**Comment by sugar700** [comment]
:-1:

**Review by QWERTYman2020 — CHANGES_REQUESTED** [review]
if you want to prevent sketchy settings you might as well remove the entire line.

**Pull request merged**
