### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by RayoGundead**
Add a code of conduct.

### CODE REVIEW

**Comment by ECrownofFire** [comment]
This isn't the place for your personal politics.

**Comment by noonien** [comment]
I doubt you have actually read the commit.

**Comment by ECrownofFire** [comment]
@noonien I did, and that is why I said it.

**Comment by noonien** [comment]
Sure you have. Then perhaps you could explain how "the golden rule" is personal politics.

**Review by nstanard — CHANGES_REQUESTED** [review]
You don't need line 2. ;)

**Comment by ECrownofFire** [comment]
@noonien I'm talking about the linked image.

**Comment by jesshillier** [comment]
distasteful

**Comment by magicgoose** [comment]
Linus probably didn't say this for real.
Would be better if you invent something more original IMO.

**Pull request closed without merging**
