### PR TITLE
Flip up and down vote emojis

### PR DESCRIPTION
**Pull request by perryprog**
@PlasmaPower I summon you 😉

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Is everybody downvoting this PR actually trying to upvote it :thinking:

**Comment by perryprog** [comment]
@PlasmaPower I'm hoping not 😛

**Comment by perryprog** [comment]
BTW you really shouldn't up vote this. It's a bad, bad idea.

**Comment by y-gupta** [comment]
👍

**Comment by perryprog** [comment]
😢 it's for the best.

**Pull request closed without merging**
