### PR TITLE
You won't believe this PR!!! Commit 3 will amaze you!!

### PR DESCRIPTION
**Pull request by rudehn**
Leave a message with the state of the vote and how long until the voting window is over.

Looks like this

image

There are also some bug fixes that are required for this to work.

### CODE REVIEW

**Comment by phil-r** [comment]
@rudehn I'm soooo amazed 😆 
But seriously - good job!

**Comment by mark-i-m** [comment]
Pretty soon the titles of our PRs are going to be completely meaning less.

**Comment by yet-another-account** [comment]
@mark-i-m `PR #3731: "b2ggaGkgdGhlcmUgby8=! "`

**Comment by mark-i-m** [comment]
How is this still at 7hrs left?

**Comment by rudehn** [comment]
I think something is broke with the status reporting. I did push to a separate branch about an hour ago. Does that reset the timer?

**Comment by mark-i-m** [comment]
Hmm... I don't know. Could you try pushing some random change now? If the timer resets back to the full window, then we know that either Github or Chaosbot is broken :smile:

**Comment by rudehn** [comment]
Yup it reset.

**Comment by mark-i-m** [comment]
Huh, well now we know... Thanks @rudehn

**Comment by rudehn** [comment]
@mark-i-m 

> def get_pr_last_updated ...
 repo = pr_data["head"]["repo"]

This is the culprit. This is repo specific, not branch specific.

**Comment by mark-i-m** [comment]
Yep... I've been looking through the GitHub API, and I think what we have to do is use `pr_data["head"]["sha"]` to get the commit sha for the HEAD of the merging branch. Then, use https://developer.github.com/v3/git/commits/ to get the commit date/time.

**Comment by PlasmaPower** [comment]
@mark-i-m BAD IDEA! Commit time can be modified with `--date`. The repo push time is the only secure way.

**Comment by rudehn** [comment]
There's also the `head` parameter when searching pull requests.

> Filter pulls by head user and branch name in the format of user:ref-name. Example: github:new-script-format.

**Comment by mark-i-m** [comment]
So then, people just shouldn't work on more than one feature at a time?

**Comment by mark-i-m** [comment]
@rudehn Could you explain how you propose using the `head` parameter more?

**Comment by mark-i-m** [comment]
Attempt 2: It looks like we might be able to use the Events API to get the last PushEvent for a repo... Then filter by the `ref` that matches the PR. But that would be a lot of work...

**Comment by mark-i-m** [comment]
In other words, we would want to do something like this:

```
pr_ref = pr["head"]["ref"]
pr_repo = pr["head"]["repo"]
pr_owner = pr["user"]["login"]

events = GET /repos/{pr_owner}/{pr_repo}/events
events = filter(events, lambda e: e["payload"]["ref"] = pr_ref)
last_updated = max(sorted(map(events, lambda e: e["created_at"])))
```

**Pull request merged**
