### PR TITLE
add timestamp and formatting to logger

### PR DESCRIPTION
**Pull request by ozyx**
So we know *when* things went wrong...

### CODE REVIEW

**Comment by reddraggone9** [comment]
Congratulations. *You* made [things go wrong](https://gitter.im/chaosthebot/Lobby?at=592700cf0a783b6c0ad4b8c8) since your indentation was off 😜

@amoffat You're also [on record supporting this](https://github.com/chaosbot/chaos/commit/ff46d4b06d5c3d97b5fbb754b9c01a1e985e33e0).

See also #237, #239, and #246.

**Comment by ozyx** [comment]
Ah, my bad! Will admit, did not test properly since dev environment had some issues getting started. Hoping after latest dev env PR things will get easier to test. 

At least we have a timestamp now, though! 😖

**Comment by patricknelson** [comment]
@ozyx Out of curiosity, what was your dev environment? Vagrant, Docker or something else?

**Comment by ozyx** [comment]
Vagrant/VirtualBox as detailed in the README

**Pull request merged**
