### PR TITLE
Use symbol emojis instead of human emojis

### PR DESCRIPTION
**Pull request by PlasmaPower**
When I'm glancing through emails, I have to look closely to see what :ok_woman: and :no_good: are. It'd be a lot easier with :no_entry: and :white_check_mark:. The different colors make it a lot clearer.

### CODE REVIEW

**Review by andrewda — APPROVED** [review]

**Comment by rhengles** [comment]
Personally, I prefer more 🆗 or ✅ than 🎉 .

**Comment by PlasmaPower** [comment]
@rhengles :white_check_mark: looks like a good choice. Changed.

Thoughts on the stale PR with merge conflicts emoji? It was :no_good:. I changed it to :broken_heart: as it's a bit different than :no_entry:. I'm reconsidering that though. Which does everyone else prefer?

**Comment by PlasmaPower** [comment]
@andrewda Re-review needed after change

**Review by rhengles — APPROVED** [review]

**Review by o3LL — APPROVED** [review]

**Review by andrewda — APPROVED** [review]

**Comment by mark-i-m** [comment]
@PlasmaPower Have you just been stockpiling PRs?

**Comment by PlasmaPower** [comment]
@mark-i-m I stockpile ideas, then sometimes I feel like doing stuff.

**Comment by PlasmaPower** [comment]
I have chaosbot's full attention - literally all the PRs it is processing right now are mine :smile:.

**Comment by mark-i-m** [comment]
Shameless plug: #420

**Comment by PlasmaPower** [comment]
@mark-i-m yeah I'm really appreciating that right now.

**Comment by PlasmaPower** [comment]
Now includes stalled CI failed message (recently merged).

**Review by rhengles — APPROVED** [review]

**Review by andrewda — APPROVED** [review]

**Pull request merged**
