### PR TITLE
Add roadmap (a link to issue Feature Requests and Ideas for Expansion wiki page from the homepage)

### PR DESCRIPTION
**Pull request by anythingbot**
Add a link to issue #473 to the homepage, [roadmap](https://github.com/chaosbot/Chaos/issues/473).

### CODE REVIEW

**Comment by PlasmaPower** [comment]
:-1: I don't like roadmaps, instead contribute whatever you want the project to have.

**Comment by ipranjal** [comment]
👎 i agree with @PlasmaPower #473 is just my personal roadmap for building an artificial intelligence over chaosbot perhaps adding it to https://github.com/chaosbot/Chaos/wiki/Notable-issues-and-PRs wont harm though thoughts ? @PlasmaPower 

Or we can add a small section on the main homepage kind of like "time for rise of terminator"

**Comment by PlasmaPower** [comment]
I like the idea of a wiki page, I think it'd work a lot better for the task.

**Comment by PlasmaPower** [comment]
Sorry, misread your comment. Good idea, but I was wondering about a separate wiki page for ideas to implement.

**Comment by andrewda** [comment]
@PlasmaPower https://github.com/chaosbot/Chaos/wiki/Feature-Requests ?

**Comment by ipranjal** [comment]
@andrewda well i guess "Feature Requests" and "Ideas" are two different stuff. valid? @PlasmaPower @andrewda

**Comment by andrewda** [comment]
Maybe we could change the name of the Feature Requests page to be more general? I kind of like having all things that we want to implement in the future on one page so it's easier to see.

**Comment by PlasmaPower** [comment]
Agreed @andrewda. Maybe something like "Feature Requests and Ideas for Expansion"?

**Comment by ipranjal** [comment]
@PlasmaPower sounds cool

**Comment by andrewda** [comment]
> "ChaosBot is a social coding experiment to see what happens when the absolute direction of a software project is turned over to the roadmap."

That doesn't sound right to me – we're not turning it over to the roadmap. I think it should be kept "open source community", but we could put the roadmap somewhere else.

**Review by andrewda — APPROVED** [review]
That sounds pretty good to me 🙂

**Comment by ipranjal** [comment]
its kinda like #479 vs #480 either one of them needs to be merged xD . The war of democracy is here ! But our meritocrates still hold the power and wisdom xD xD

**Comment by Swizz** [comment]
:-1: Like I said in https://github.com/chaosbot/Chaos/issues/460#issuecomment-305492601, we do not need roadmap. we need selfish roadmap, on a global democratic project to see where we are going to.

You can have your own project, or a group project inside the community. But not a global community project. This is not my thoughts about Chaos

**Pull request closed without merging**
