### PR TITLE
Better supervisor config

### PR DESCRIPTION
**Pull request by amoffat**
let's try this again #146, now that we have a democracy back
-----
now that we have http://chaosthebot.com:8081/ for logs, let's make the log files a little more manageable

also, we'll lean on supervisor for restarting things

### CODE REVIEW

**Comment by rhengles** [comment]
What happened that this was merged *immediately*?

**Comment by amoffat** [comment]
@rhengles I can tell you why it merged right away, but I can't tell you why the [vote threshold](https://github.com/chaosbot/chaos/commit/bb16740df1e344287ae0baaefbc8a6065f7e67cf) was only 1.0.  It merged due to a bug that hasn't been patched yet, where if a downstream branch sits for longer than the voting window, before a PR is opened, then a PR is opened, chaos thinks its ready to be approved.  Needs to be patched ASAP

**Comment by rudehn** [comment]
oh that's bad

**Comment by hongaar** [comment]
@amoffat Vote threshold was only 1.0 because at the time this was merged, #152 was not merged yet.

**Pull request merged**
