### PR TITLE
Fix center and responsive website.

### PR DESCRIPTION
**Pull request by Alexays**
Fix firefox center.
On mobile cards take 85% of width to allow to click on other.

### CODE REVIEW

**Review by o3LL — APPROVED** [review]

**Comment by rudehn** [comment]
This meritocracy review is throwing everybody off. Gotta get used to it.

**Comment by o3LL** [comment]
@rudehn I was the only one reviewing... Maybe reduce minimum review needed

**Comment by rudehn** [comment]
Well you only need 1 review. Are you in the meritocracy list?

**Comment by o3LL** [comment]
I was, didnt checked if I still in but yeah I think

**Comment by andrewda** [comment]
@MUCHZER you _should_ be because you're the 6th ranked contributor, but you're not in the list... Seems like a bug.

**Pull request closed without merging**
