### PR TITLE
easy replication

### PR DESCRIPTION
**Pull request by larsnolden**
Spread Chaosbot on Ubuntu machines via ssh!
The index.html in the repo won't merge right for some reason...

### CODE REVIEW

**Comment by ozyx** [comment]
You included your `node_modules`...

**Comment by larsnolden** [comment]
Yes, with intention. It should come out without someone having to install them manually.

**Comment by ozyx** [comment]
@larsnolden that's kind of the whole purpose of `npm`

**Comment by rhengles** [comment]
> Yes, with intention. It should come out without someone having to install them manually.

what

**Comment by larsnolden** [comment]
Haha, am I missing something?
Should I have had bundled the modules into one production file?
I am not using webpack or any other bundler.

Or should the bot install the dep's on its own via the startup.sh?

Edit: Setting up Webpack now to bundle the modules.

**Comment by arunoda** [comment]
@larsnolden when you have a package.json file you can simply run "npm install" to get these modules.

I didn't read the build setup, but I hope there should be a place to add the command : "npm install"

**Pull request closed without merging**
