### PR TITLE
[WIP] Zenofchaos propose

### PR DESCRIPTION
**Pull request by eamanu**
This is a proposal to have a Zen of Chaos.
We can complete the Zen with the principles that we consider important

### CODE REVIEW

**Comment by davidak** [comment]
I don't see myself represented in these principles.

I'm also not sure if we need a Zen of Chaos at all. Maybe if someone comes with some inspiring or funny principles. Suggestions can be made in the comments.

**Comment by davidak** [comment]
- The chaos inspire us to get new ideas and explore new things.

**Comment by eamanu** [comment]
I not pretend make 'Chaos' my religion (hehe), but I thought that maybe fun

**Comment by phil-r** [comment]
`Religion` is a very strong word... Chaos is a fun and interesting project, but it's not a religion and I hope it will never be it.

**Pull request closed without merging**
