### PR TITLE
[WIP] Display current votes as GitHub status

### PR DESCRIPTION
**Pull request by hongaar**
Todo:

- [x] Optimise loops (it runs through some PRs twice now)
- [x] Add hours left in status description?
- [x] Add votes count?

Any help/input is appreciated.

See https://developer.github.com/v3/repos/statuses/ for API reference

Demo here: https://github.com/hongaar/chaos/pull/1

PR overview:

image

PR detail:

image

### CODE REVIEW

**Comment by rudehn** [comment]
Will this post duplicate comments?

**Comment by ctian1** [comment]
It doesn't seem to post comments.

**Comment by hongaar** [comment]
@rudehn No, it posts only a new PR status, which can contain a description:

image

**Comment by hongaar** [comment]
With latest update:

image

**Comment by amoffat** [comment]
looking good @hongaar !

**Comment by hongaar** [comment]
Closing this in favour of #148

**Pull request closed without merging**
