### PR TITLE
Need more chaos

### PR DESCRIPTION
**Pull request by Zidail**
1pk557

### CODE REVIEW

**Comment by DasSkelett** [comment]
Nope, in order to prevent PRs like this.

**Comment by ghost** [comment]
Outstanding attempt, though.  I kinda want to +1 it just for that...

**Comment by b0o** [comment]
👎 sorry :(

**Review by drindc24 — APPROVED** [review]

**Comment by rhengles** [comment]
What

**Comment by mrhwick** [comment]
Well that didn't take long.

**Comment by Ajedi32** [comment]
Uh... so is there a bug in the vote counting code or something? The merge commit (9500e94fbb90a5589b92242ff28ef173836cc4e6) claims there were only two votes on this PR (both in favor), when in reality there were over a hundred.

**Comment by geekyi** [comment]
Possible explanation for why this got merged: https://github.com/chaosbot/chaos/issues/82#issuecomment-303518208

**Pull request merged**
