### PR TITLE
Speed up chaos canvas on website

### PR DESCRIPTION
**Pull request by jakejdavis**

### CODE REVIEW

**Comment by phil-r** [comment]
why not use `window.requestAnimationFrame()` ?

**Comment by PlasmaPower** [comment]
:-1: I like the idea of the change, but `requestAnimationFrame` is the way to go.

**Comment by phil-r** [comment]
@jakejdavis resubmit with `requestAnimationFrame` and I will upvote it ;)

**Comment by jakejdavis** [comment]
@phil-r @PlasmaPower I have created a new pull request using requestAnimationFrame found at #320 :)

**Pull request closed without merging**
