### PR TITLE
Add ASCII chicken game

### PR DESCRIPTION
**Pull request by xyproto**
Add a small image of an ASCII chicken that you can move with the arrow keys.

### CODE REVIEW

**Comment by keithstellyes** [comment]
:+1: yessir

**Comment by xyproto** [comment]
Fixed merge conflict on mobile phone over ssh. Anything could happen.

**Comment by davidak** [comment]
I'm vegan so i downvote this :D

Animals are living creatures and nothing to play with.

**Comment by xyproto** [comment]
Not even puppies?

**Comment by davidak** [comment]
Actually i just don't like the idea to have a chicken game in this.

If puppies want to play with you it's fine to do so.

**Comment by xyproto** [comment]
It's an *ASCII chicken*.

**Pull request merged**
