### PR TITLE
Fix voters scoreboard

### PR DESCRIPTION
**Pull request by Swizz**
chaos bug on voters.html

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I was wondering if that change was intentional in the other PR...

**Comment by PlasmaPower** [comment]
Also fix top voters please.

**Comment by andrewda** [comment]
https://github.com/chaosbot/Chaos/blob/master/server/static/js/chaos.js#L146

**Comment by mark-i-m** [comment]
@andrewda Does the script you linked also need to be updated?

**Comment by andrewda** [comment]
Yes. However, all of these should be working when with the new [`webserver.py`](https://github.com/chaosbot/Chaos/blob/master/webserver.py) – not sure why it isn't working.

**Comment by mark-i-m** [comment]
@Swizz I am withholding my vote until the thing @andrewda pointed out gets sorted

**Comment by PlasmaPower** [comment]
Odd. `/voters` and `/voters.json` both work fine locally in docker. However, at http://chaosthebot.com  only `/voters.json` works.

**Comment by andrewda** [comment]
@PlasmaPower Yea it's working in Docker for me, too. Not sure what's up with the production site...

**Comment by mdcfe** [comment]
@andrewda Did you link/copy the new nginx config `chaos_uwsgi` on prod?

**Pull request closed without merging**
