### PR TITLE
Make @smittyvb votes worth about (e^pi-pi)/40

### PR DESCRIPTION
**Pull request by yet-another-account**
Repost of #338

### CODE REVIEW

**Comment by PlasmaPower** [comment]
:-1: why even bother?

**Comment by PlasmaPower** [comment]
> chaosbot — remaining: -2:09, vote: 6-0, weighted total: 5.5, threshold: 6.5

Hmm so it wasn't just #350 - any idea what's going on?

**Comment by rudehn** [comment]
2 minutes from start to rejection :feelsbadman

**Comment by phil-r** [comment]
it's a sign 🛑

**Comment by rudehn** [comment]
a stop sign? :laughing:

**Pull request closed without merging**
