### PR TITLE
There was an unfortunate lack of cats.

### PR DESCRIPTION
**Pull request by hawkfalcon**
This is the internet, after all.

### CODE REVIEW

**Comment by agargiulo** [comment]
👎 No gifs in readmes ⛔️

**Comment by hawkfalcon** [comment]
Would you prefer sourcing from http://thecatapi.com/api/images/get?format=src&type=png ?

**Comment by agargiulo** [comment]
Eh, it would be better but still kinda obnoxious more than chaotic. Is there at least a way to make them not MASSIVE?

**Comment by hawkfalcon** [comment]
Yep, looks like there is a size parameter which takes small, medium, or large. Will create new PR.

**Pull request closed without merging**
