### PR TITLE
Implementing the DB stuff

### PR DESCRIPTION
**Pull request by rudehn**
This introduces the database into chaosbot. Currently on my fork, the issue commands and meritocracy tables are implemented and working, and those are provided with this PR.

The API for the database ORM is pretty simple. See [here](http://docs.peewee-orm.com/en/latest/peewee/quickstart.html) for a quickstart to doing various operations.

Hope you all enjoy! This took a surprising amount of work to get implemented.

### CODE REVIEW

**Comment by rudehn** [comment]
Yeah it's a big update and a lot of stuff is conflicting. Looking to finish this up tomorrow.

**Comment by rudehn** [comment]
OK not sure why this got screwed up when I did the rebase. The DB stuff is tested and working. I would appreciate advice on how to clean this stuff up.

**Comment by andrewda** [comment]
With 35 files changes, I'd say if it's working this should get merged ASAP so there aren't a ton of conflicts. Then we can worry about cleaning it up a little in future PR's.

**Comment by rudehn** [comment]
Yeah it's been WIP for a few days, so when I resolved the conflicts, it updated literally everything. Not sure if there's a way to get around that.

**Comment by mark-i-m** [comment]
This could be very messy if you try to merge it I think... I've seen things like this happen which actually really messed up the git history of master. I would recommend generating a patch with the diff between your branch and chaosbot master. Then apply the patch on a fresh branch and submit a new PR.

**Comment by rudehn** [comment]
Sounds good @mark-i-m. I've decided to leave it WIP until I can figure out how to clean it up. I'll try your suggestion

**Comment by PlasmaPower** [comment]
I'll see if I can clean it up for you.

**Comment by andrewda** [comment]
@mark-i-m Yea, you're right. That's probably the cleanest way to go about it.

**Comment by rudehn** [comment]
Thanks @PlasmaPower, appreciate it.

A task still to do is migrate the current data into the db.

**Comment by PlasmaPower** [comment]
@rudehn done! To apply my branch:

```sh
git fetch https://github.com/PlasmaPower/chaos.git db-rebase
git reset --hard FETCH_HEAD
```

From there, check that everything looks right, then `git push --force` to push it to GitHub.

**Comment by PlasmaPower** [comment]
A migration script isn't a huge deal right now, worst case a couple of comment votes get dropped and the meritocracy gets mentioned an extra time.

**Comment by rudehn** [comment]
Hey it worked! Thanks! How did you do it?

**Comment by PlasmaPower** [comment]
~A magician never reveals his secrets~

1. checkout and pull master
2. create `db-rebase` branch
3. fetch your branch so I can get commits from it
4. cherry pick commits from this branch, ignoring ones that are changes on master
5. push

**Comment by PlasmaPower** [comment]
To list the commits, I used `git log` of course.

**Comment by PlasmaPower** [comment]
Oops looks like I missed a commit?

**Comment by PlasmaPower** [comment]
Or was that a local change? I think so.

**Comment by rudehn** [comment]
No that was a merge error on my part.

**Comment by rudehn** [comment]
This is just waiting review now. I can un-WIP if needed.

**Review by PlasmaPower — APPROVED** [review]
The ORM makes things a lot easier!

**Review by andrewda — APPROVED** [review]

**Comment by PlasmaPower** [comment]
For the record, this resulted in all issue commands revoting, as expected. There were a lot more than I thought though.

**Comment by andrewda** [comment]
... And it's repeating.

**Comment by rudehn** [comment]
I've created a monster.

I'm not sure what the exact issue is, but it's one of the following

- The active command is not being transferred to the inactive command list.
- The `since` param isn't working and all issue comments are being retrieved

**Pull request merged**
